// Glossaire InvestKit — rédigé pour un débutant complet.
// Chaque entrée : id (utilisé par l'icône « ? »), terme, explication simple, et « Dans le jeu » quand le
// simulateur applique une règle précise. Les taux et seuils du jeu sont des simplifications pédagogiques.
export const GLOSSARY_CATEGORIES = {
  credit: 'Le crédit',
  achat: 'L\'achat',
  location: 'La location',
  impots: 'Les impôts',
  vente: 'La revente',
  bourse: 'Bourse et crypto',
  jeu: 'Dans le jeu',
};

export const GLOSSARY = [
  // ── Bourse et crypto
  { id: 'courtage', category: 'bourse', term: 'Courtage (frais d\'ordre)',
    short: 'Une petite commission payée à chaque achat et à chaque vente.',
    long: 'Le courtier qui passe tes ordres se rémunère en prenant un petit pourcentage du montant (avec un minimum). En France, sur un PEA, il ne peut pas dépasser 0,5 % d\'un ordre passé en ligne. Ces frais grignotent la performance : acheter et revendre sans arrêt coûte cher.',
    inGame: 'Les pièces payées en courtage disparaissent (elles ne sont données à personne). Taux : 0,5 % (actions), 0,35 % (ETF), 0,5 % (crypto), minimum 1 🪙. Taux de jeu inspirés de courtiers réels, à reconfirmer.' },
  { id: 'pea', category: 'bourse', term: 'PEA (plan d\'épargne en actions)',
    short: 'Une enveloppe qui exonère d\'impôt sur le revenu les gains retirés après 5 ans.',
    long: 'Tu y loges des actions et des ETF européens. Si tu retires après 5 ans, tu ne paies plus d\'impôt sur le revenu sur les gains, seulement les prélèvements sociaux (18,6 % en 2026). Avant 5 ans, un retrait est taxé à la flat tax. Les versements sont plafonnés à 150 000 €.',
    inGame: 'Le compteur des 5 ans démarre à ton premier achat en PEA. Simplifications : le PEA n\'est jamais clôturé et les prélèvements sociaux sont au taux de l\'année de la vente.' },
  { id: 'compte-titres', category: 'bourse', term: 'Compte-titres ordinaire (CTO)',
    short: 'L\'enveloppe sans avantage fiscal : chaque plus-value est taxée à la flat tax.',
    long: 'Aucune limite de montant ni de durée, mais tes gains sont imposés à chaque vente (flat tax : 12,8 % d\'impôt + prélèvements sociaux, soit 31,4 % en 2026).' },
  { id: 'flat-tax', category: 'bourse', term: 'Flat tax (prélèvement forfaitaire unique)',
    short: 'Un impôt à taux unique sur les plus-values : 12,8 % + prélèvements sociaux.',
    long: 'Depuis 2018, les gains sur titres et sur cryptomonnaies sont taxés à un taux fixe. Les prélèvements sociaux valent 17,2 % (18,6 % en 2026), soit 30 % puis 31,4 % au total.',
    inGame: 'Avant 2018, le jeu applique un taux simple de 19 % à la place du barème réel (simplification). Pas de report des moins-values.' },
  { id: 'impot-crypto', category: 'bourse', term: 'Impôt sur les cryptos',
    short: 'Tu ne paies un impôt que lorsque tu revends tes cryptos contre des euros.',
    long: 'Échanger une crypto contre une autre n\'est pas imposé ; seule la vente vers l\'euro (ou un achat avec tes cryptos) l\'est, à la flat tax. Si le total de tes ventes de l\'année ne dépasse pas 305 €, tu ne paies rien.',
    inGame: 'Toute vente de crypto se fait contre InvestCoins : elle est donc imposable. Le seuil de 305 🪙 est suivi année par année. Simplification : les gains des ventes déjà faites sous le seuil ne sont pas rattrapés.' },
  { id: 'action', category: 'bourse', term: 'Action',
    short: 'Une petite part d\'une entreprise. Si l\'entreprise vaut plus, ta part vaut plus.',
    long: 'En achetant une action, tu deviens copropriétaire d\'une entreprise cotée en Bourse. Son prix monte et descend selon les résultats de l\'entreprise et l\'humeur des investisseurs. Tu peux gagner, mais aussi perdre.',
    inGame: 'Tu achètes et vends avec tes InvestCoins, aux cours historiques réels de l\'année simulée.' },
  { id: 'etf', category: 'bourse', term: 'ETF (fonds indiciel)',
    short: 'Un « panier » d\'actions achetable en une seule fois, qui copie un grand indice.',
    long: 'Au lieu de choisir une entreprise, tu achètes un panier qui en contient des centaines. C\'est un moyen simple de répartir ton risque. Le prix du panier varie avec la moyenne des entreprises qu\'il contient.' },
  { id: 'obligation', category: 'bourse', term: 'Obligation',
    short: 'Un prêt que tu fais à un État ou à une entreprise, contre des intérêts.',
    long: 'Tu prêtes de l\'argent et on te le rend plus tard avec un intérêt. En général, c\'est moins risqué et moins rémunérateur que les actions.' },
  { id: 'crypto', category: 'bourse', term: 'Cryptomonnaie',
    short: 'Une monnaie numérique (Bitcoin, Ethereum…) dont le prix varie très fortement.',
    long: 'Il n\'y a ni entreprise ni État derrière : le prix ne dépend que de l\'offre et de la demande. Il peut doubler ou perdre la moitié de sa valeur en peu de temps. C\'est l\'actif le plus risqué du jeu.',
    inGame: 'Le crédit sur portefeuille est plus prudent en crypto (on te prête moins) car les prix bougent beaucoup.' },
  { id: 'volatilite', category: 'bourse', term: 'Volatilité',
    short: 'À quel point le prix monte et descend brutalement. Plus c\'est élevé, plus c\'est risqué.',
    long: 'Un actif peu volatil bouge doucement ; un actif très volatil peut gagner ou perdre beaucoup en peu de temps. Ce n\'est pas « mauvais » en soi, mais il faut pouvoir supporter les baisses.' },
  { id: 'diversification', category: 'bourse', term: 'Diversification',
    short: 'Ne pas mettre tous ses œufs dans le même panier.',
    long: 'En répartissant ton argent entre plusieurs actifs (actions, ETF, obligations, crypto), une mauvaise nouvelle sur l\'un d\'eux pèse moins sur l\'ensemble.' },
  { id: 'cours-cloture', category: 'bourse', term: 'Cours de clôture annuel',
    short: 'Le prix d\'un actif à la fin de l\'année. C\'est le seul prix que le jeu utilise.',
    long: 'Dans la vraie vie les prix changent à chaque seconde. Ici, pour simplifier, on ne connaît que le prix de fin d\'année : un actif a pu s\'effondrer en cours d\'année puis remonter sans que tu le voies.',
    inGame: 'Simplification pédagogique : les appels de marge et ventes forcées se calculent aussi sur ces prix annuels.' },
  { id: 'annee-simulee', category: 'bourse', term: 'Année simulée',
    short: 'L\'année du jeu où tu te trouves. Tu peux la faire avancer d\'un an à la fois.',
    long: 'Le temps ne passe pas tout seul : c\'est toi qui avances. Les prix changent alors pour de bon, tes intérêts éventuels sont payés, et tu vois si tes choix ont été bons.',
    inGame: 'Bourse et Crypto avancent par années ; l\'Immobilier avance par mois. Chaque domaine a sa propre horloge.' },
  { id: 'valeur-positions', category: 'bourse', term: 'Valeur des positions',
    short: 'Ce que valent, au prix du jour, tous les titres que tu détiens.',
    long: 'C\'est le nombre de titres multiplié par leur cours. Ce n\'est qu\'une valeur « sur le papier » tant que tu n\'as pas vendu.' },
  { id: 'performance-portefeuille', category: 'bourse', term: 'Performance du portefeuille',
    short: 'Ton gain ou ta perte en pourcentage depuis le départ.',
    long: 'Elle compare ce que tu possèdes maintenant (pièces + titres) à ce que tu avais au départ. Si tu as emprunté, le classement tient compte de la dette.',
    inGame: 'Classement en richesse nette de dettes, avec mention du levier utilisé.' },
  // ── Le crédit
  { id: 'credit', category: 'credit', term: 'Crédit immobilier',
    short: 'Un prêt de la banque pour acheter un bien, remboursé chaque mois pendant des années.',
    long: 'Tu empruntes une somme à la banque et tu la rends par petits morceaux (les mensualités), avec un supplément : les intérêts. Tant que le prêt n\'est pas fini, le bien sert de garantie à la banque.',
    inGame: 'Durée de 10 à 30 ans. La banque accepte ou refuse ton dossier et t\'explique pourquoi.' },
  { id: 'mensualite', category: 'credit', term: 'Mensualité',
    short: 'La somme que tu paies à la banque chaque mois.',
    long: 'Elle reste la même pendant tout le prêt. Elle contient trois choses : du capital remboursé, des intérêts et l\'assurance emprunteur.' },
  { id: 'capital-rembourse', category: 'credit', term: 'Capital remboursé',
    short: 'La part de ta mensualité qui diminue vraiment ta dette. Cet argent n\'est pas perdu : il t\'enrichit.',
    long: 'Chaque mois, une partie de la mensualité rembourse la somme empruntée. Ta dette baisse, donc la part du bien qui t\'appartient réellement augmente. Au début du prêt cette part est petite, elle grossit avec le temps.',
    inGame: 'Affiché séparément de l\'effort d\'épargne, car ce n\'est pas une dépense : c\'est de la richesse qui se construit.' },
  { id: 'interets', category: 'credit', term: 'Intérêts',
    short: 'Le prix que tu paies à la banque pour lui avoir emprunté de l\'argent.',
    long: 'Ils sont calculés sur ce qu\'il te reste à rembourser. Ils sont donc plus élevés au début du prêt. C\'est une vraie dépense, mais elle est déductible de tes revenus de loyers pour le calcul de l\'impôt.' },
  { id: 'taux', category: 'credit', term: 'Taux d\'intérêt',
    short: 'Le pourcentage que la banque te fait payer chaque année sur la somme empruntée.',
    long: 'Plus il est bas, moins le crédit coûte cher. Il change selon les années : un même bien peut être facile à financer une année et bien plus cher à financer une autre.',
    inGame: 'Le taux dépend de l\'année de jeu et de la durée choisie.' },
  { id: 'taeg', category: 'credit', term: 'TAEG',
    short: 'Le vrai coût du crédit en pourcentage : intérêts, assurance et frais compris.',
    long: 'Le taux annoncé ne dit pas tout. Le TAEG (taux annuel effectif global) ajoute l\'assurance et les frais de dossier. C\'est le chiffre à comparer entre deux offres.' },
  { id: 'assurance-emprunteur', category: 'credit', term: 'Assurance emprunteur',
    short: 'Une assurance qui rembourse la banque si tu ne peux plus payer (décès, invalidité).',
    long: 'Les banques l\'exigent presque toujours. Elle s\'ajoute à la mensualité.' },
  { id: 'apport', category: 'credit', term: 'Apport',
    short: 'L\'argent que tu mets de ta poche au départ, pour ne pas tout emprunter.',
    long: 'Plus l\'apport est élevé, moins tu empruntes, et plus la mensualité est légère. Les banques demandent en général au moins de quoi couvrir les frais de notaire.',
    inGame: 'Tu le paies en InvestCoins (1 🪙 = 20 € dans l\'Immobilier).' },
  { id: 'endettement', category: 'credit', term: 'Taux d\'endettement',
    short: 'La part de tes revenus qui part en remboursement de crédits.',
    long: 'La banque calcule : mensualités ÷ revenus. Au-delà d\'un certain seuil, elle refuse. Elle ne compte qu\'une partie des loyers que le bien rapportera, par prudence.' },
  { id: 'reste-a-vivre', category: 'credit', term: 'Reste à vivre',
    short: 'Ce qu\'il te reste chaque mois une fois le crédit et tes dépenses courantes payés.',
    long: 'Même si ton taux d\'endettement est correct, la banque vérifie qu\'il te reste assez pour vivre.' },
  { id: 'capital-restant', category: 'credit', term: 'Capital restant dû',
    short: 'Ce que tu dois encore à la banque à un instant donné.',
    long: 'Au début, il baisse lentement ; à la fin, plus vite. Quand tu vends, la banque récupère cette somme sur le prix de vente.' },
  { id: 'levier', category: 'credit', term: 'Effet de levier',
    short: 'Acheter un bien plus cher que ce que tu possèdes grâce au crédit.',
    long: 'Si le bien prend de la valeur, tu gagnes sur toute sa valeur alors que tu n\'as avancé qu\'une partie. Mais s\'il en perd, ou si les loyers ne suffisent pas, tu perds aussi plus : le levier agit dans les deux sens.' },

  // ── La banque
  { id: 'pret-personnel', category: 'credit', term: 'Prêt personnel',
    short: 'Un prêt sans garantie, plafonné selon tes revenus, à un taux plus élevé qu\'un prêt immobilier.',
    long: 'La banque ne prend pas ton bien en garantie : elle est donc plus prudente (montant limité) et plus chère (taux plus haut). Chaque mensualité compte dans ton taux d\'endettement, ce qui réduit ta capacité à emprunter pour acheter un bien.',
    inGame: 'Plafond : 6 mois de revenus nets de ton profil. Taux : taux de base de l\'année + 4,5 points (fictif, non sourcé). Réservé à l\'Immobilier. Un seul prêt à la fois.' },
  { id: 'credit-fleche', category: 'credit', term: 'Crédit fléché (prêt affecté)',
    short: 'Un prêt dont l\'argent ne peut servir qu\'à un usage précis.',
    long: 'Comme un prêt « affecté » réel : l\'argent est prévu pour un projet. Ici, les pièces empruntées sont réservées à un domaine (l\'Immobilier pour le prêt personnel) et ne peuvent pas être dépensées ailleurs. Cela évite qu\'un emprunt dans un domaine serve à jouer dans un autre où les pièces n\'ont pas la même valeur.',
    inGame: 'Les pièces réservées sont dépensées en premier dans leur domaine. Tes propres pièces restent libres partout.' },
  { id: 'taux-base', category: 'credit', term: 'Taux de base',
    short: 'Le taux de référence de l\'année, auquel la banque ajoute sa marge selon le risque.',
    long: 'Un prêt garanti par un bien coûte moins cher qu\'un prêt sans garantie : la banque ajoute une marge plus grande quand elle prend plus de risque.',
    inGame: 'Taux de base fictif calé sur l\'histoire (valeur de jeu, non sourcée, à reconfirmer) + un écart par produit.' },
  { id: 'retablissement', category: 'credit', term: 'Procédure de rétablissement',
    short: 'Un dernier recours après un défaut : la dette du domaine est effacée, mais tout ce domaine repart de zéro.',
    long: 'Pour éviter qu\'un joueur reste bloqué pour toujours, il peut demander l\'effacement d\'une dette qu\'il ne peut pas payer. En contrepartie, il perd ce qu\'il avait dans ce domaine (titres ou biens), son rang, et il ne peut plus emprunter pendant un mois. Ce n\'est pas gratuit, ni illimité.',
    inGame: 'Au plus 3 procédures par compte, espacées de 30 jours (temps réel). Capital de base de 500 🪙 seulement si tu as moins. Les badges de domaine seront retirés quand ils seront rattachés au serveur.' },
  { id: 'pret-portefeuille', category: 'credit', term: 'Prêt sur portefeuille (Lombard)',
    short: 'Un prêt garanti par tes titres : tu empruntes en gardant tes actions ou ta crypto.',
    long: 'La banque te prête une partie de la valeur de tes titres (moins pour les actifs très volatils). Tu paies des intérêts, et ta garantie est réévaluée : si les cours baissent trop, la banque te demande d\'ajouter de la garantie ou de rembourser, sinon elle vend tes titres à ta place. Le levier augmente les gains, mais aussi les pertes.',
    inGame: 'Prêt maximum : 50 % de la valeur des actions, 30 % de la crypto. Taux variable = taux de base + 2 points (non sourcé). Intérêts payés à chaque passage d\'année. Un seul prêt par domaine.' },
  { id: 'appel-de-marge', category: 'credit', term: 'Appel de marge et vente forcée',
    short: 'Quand tes titres perdent trop de valeur, la banque exige de la garantie en plus, ou vend tes titres.',
    long: 'On compare la dette à la valeur des titres (le « rapport prêt/valeur »). Au-delà d\'un premier seuil, c\'est l\'appel de marge : tu dois rembourser une partie ou ajouter des titres. Au-delà d\'un second seuil, ou si tu ne fais rien, la banque vend une partie de tes titres, avec une décote, pour ramener la dette à un niveau sûr. Si la vente ne suffit pas, il te reste une dette.',
    inGame: 'Actions : appel à 65 %, vente forcée à 80 % (crypto : 39 % et 48 %). Simplification : les cours sont des clôtures annuelles, donc tout est évalué seulement au passage d\'une année ; dans la réalité, un krach en cours d\'année déclenche l\'appel tout de suite.' },
  { id: 'defaut-paiement', category: 'credit', term: 'Défaut de paiement',
    short: 'Quand tu ne rembourses plus ton prêt : la dette reste due et la banque ne te prête plus rien.',
    long: 'Une échéance manquée n\'efface pas la dette. Après plusieurs échéances impayées de suite, le prêt est déclaré en défaut : tu dois toujours l\'argent et tu ne peux plus emprunter tant qu\'il n\'est pas soldé.',
    inGame: '3 échéances impayées de suite = défaut. Le blocage se lève quand le prêt est soldé.' },
  { id: 'remboursement-anticipe', category: 'credit', term: 'Rembourser un prêt par anticipation',
    short: 'Solder un prêt avant la fin : tu économises des intérêts, mais la banque te fait payer une indemnité.',
    long: 'Plus il reste de temps, plus la banque perd d\'intérêts, donc plus l\'indemnité est élevée (dans la réglementation du crédit à la consommation, environ 1 % du capital si plus d\'un an reste, 0,5 % sinon).',
    inGame: 'Ces repères sont à reconfirmer sur les textes officiels.' },

  // ── L'achat
  { id: 'frais-notaire', category: 'achat', term: 'Frais de notaire',
    short: 'Les frais payés à l\'achat, surtout des taxes reversées à l\'État.',
    long: 'Le notaire authentifie la vente. La plus grande partie de ces frais sont des taxes. Ils sont plus élevés dans l\'ancien que dans le neuf.',
    inGame: 'Environ 7,5 % du prix dans l\'ancien, 2,5 % dans le neuf (simplification).' },
  { id: 'frais-dossier', category: 'achat', term: 'Frais de dossier',
    short: 'Ce que la banque facture pour monter ton prêt.',
    long: 'C\'est une petite somme payée une seule fois, au début.' },
  { id: 'expertise', category: 'achat', term: 'Expertise',
    short: 'Une visite d\'un professionnel qui repère les défauts cachés avant que tu achètes.',
    long: 'Une annonce ne dit pas tout : humidité, toiture, électricité… L\'expertise coûte un peu, mais peut t\'éviter une grosse surprise de travaux.' },
  { id: 'valeur-verte', category: 'achat', term: 'Valeur verte',
    short: 'Un logement économe en énergie se vend plus cher qu\'un logement mal classé.',
    long: 'Les études des notaires montrent que la note énergétique (DPE) pèse sur le prix : un appartement perd en moyenne environ 4 % par classe perdue (environ −12 % en classe G par rapport à D), et une maison environ 8 % par classe (environ −25 % en G, environ +17 % en A). Rénover pour gagner des classes peut donc faire monter la valeur du bien, en plus de permettre de le louer.',
    inGame: 'Effet sur les prix et la valeur, par rapport à la classe D. Les valeurs sourcées sont reprises (appartement G −12 %, maison G −25 %, maison A +17 %) ; les autres sont extrapolées (non sourcées, à reconfirmer). Le loyer a son propre effet énergie.' },
  { id: 'travaux', category: 'achat', term: 'Travaux',
    short: 'Les dépenses pour remettre un bien en état.',
    long: 'Les travaux annoncés sont dans l\'annonce. Ceux qui sont cachés apparaissent après l\'achat. Un bien à rénover est moins cher, mais te coûte du temps et de l\'argent.' },
  { id: 'bonne-affaire', category: 'achat', term: 'Vente pressée',
    short: 'Un vendeur qui doit vendre vite (succession, divorce, mutation) et accepte un prix plus bas.',
    long: 'Ces occasions existent dans la réalité. Un prix plus bas améliore le rendement, mais vérifie toujours l\'état du bien.' },

  // ── La location
  { id: 'cash-flow', category: 'location', term: 'Cash-flow',
    short: 'L\'argent qui entre moins l\'argent qui sort, chaque mois, pour un bien.',
    long: 'Loyers encaissés, moins charges, moins mensualité du crédit, moins impôts. S\'il est négatif, tu dois compléter de ta poche.' },
  { id: 'effort-epargne', category: 'location', term: 'Effort d\'épargne mensuel',
    short: 'Ce que tu dois ajouter chaque mois pour que le bien « tienne » quand les loyers ne suffisent pas.',
    long: 'Avec un crédit long, un cash-flow négatif est normal : la mensualité contient du capital remboursé, qui te constitue un patrimoine. L\'effort d\'épargne est donc une façon d\'épargner, à condition que le bien garde sa valeur et reste loué.',
    inGame: 'Calculé sur un mois normal, sans les événements exceptionnels (dépôt de garantie, travaux imprévus…).' },
  { id: 'loyer', category: 'location', term: 'Loyer',
    short: 'La somme que le locataire te paie chaque mois.',
    long: 'Il dépend de la ville, du quartier, de la taille, de l\'état et de la performance énergétique. Un loyer trop haut allonge le temps sans locataire.' },
  { id: 'rendement-brut', category: 'location', term: 'Rendement brut',
    short: 'Les loyers d\'une année divisés par le prix d\'achat.',
    long: 'C\'est un repère rapide pour comparer deux biens. Il ignore les charges, les impôts et le crédit ; le rendement réel est plus bas.' },
  { id: 'rendement-metropole', category: 'location', term: 'Pourquoi les grandes villes rapportent moins',
    short: 'Les métropoles chères ont des rendements plus faibles : le prix monte plus vite que les loyers.',
    long: 'Dans une grande ville très demandée, les logements sont chers mais les loyers ne le sont pas dans les mêmes proportions : le rendement brut tourne souvent autour de 3 à 5 %. En contrepartie, le logement se loue vite et son prix a tendance à tenir dans la durée. Dans une petite ville, le rendement est plus élevé, mais le risque de mois sans locataire ou de baisse de prix aussi. Quand les taux de crédit sont élevés, les métropoles s\'autofinancent très difficilement : c\'est réaliste, pas une erreur du jeu.',
    inGame: 'Marvelle (métropole) a volontairement un rendement faible ; Ternelle ou Brumevalle rapportent plus, avec plus de risque.' },
  { id: 'vacance', category: 'location', term: 'Vacance locative',
    short: 'Les mois où le logement est vide : pas de loyer, mais les charges continuent.',
    long: 'Elle est plus courte dans une ville où il y a beaucoup de demande (zone tendue) et plus longue dans une ville qui se vide. Baisser le loyer raccourcit la vacance.' },
  { id: 'zone-tendue', category: 'location', term: 'Zone tendue',
    short: 'Une zone où il y a bien plus de demandeurs de logements que de logements.',
    long: 'Les règles y sont différentes : par exemple le préavis du locataire y est d\'un mois au lieu de trois.' },
  { id: 'charges-recuperables', category: 'location', term: 'Charges récupérables',
    short: 'Des frais que tu avances mais que le locataire te rembourse (eau, entretien des parties communes…).',
    long: 'Elles n\'ont pas d\'effet sur ton résultat, sauf quand le logement est vide ou que le locataire ne paie pas.' },
  { id: 'charges-non-recuperables', category: 'location', term: 'Charges non récupérables',
    short: 'Les frais qui restent pour toi : taxe foncière, assurance du propriétaire, entretien, part de copropriété.',
    long: 'Elles pèsent sur ton cash-flow chaque année, que le bien soit loué ou non.' },
  { id: 'taxe-fonciere', category: 'location', term: 'Taxe foncière',
    short: 'Un impôt local que paie chaque année le propriétaire.',
    long: 'Elle dépend de la commune et de la taille du bien. Elle est déductible de tes revenus de loyers.' },
  { id: 'depot-garantie', category: 'location', term: 'Dépôt de garantie',
    short: 'Une somme versée par le locataire, gardée « en dépôt » pour couvrir d\'éventuels dégâts ou impayés.',
    long: 'Ce n\'est pas un revenu : tu dois le rendre en partant, moins les retenues justifiées (dégradations, loyers non payés).',
    inGame: 'Un mois de loyer. Il n\'est jamais compté dans ton cash-flow normal.' },
  { id: 'preavis', category: 'location', term: 'Préavis',
    short: 'Le délai entre l\'annonce du départ du locataire et son départ réel.',
    long: 'Pendant le préavis, le locataire paie son loyer.',
    inGame: 'Un mois en zone tendue ou pour certains motifs, trois mois sinon.' },
  { id: 'gli', category: 'location', term: 'Assurance loyers impayés (GLI)',
    short: 'Une assurance qui te rembourse les loyers que le locataire ne paie pas.',
    long: 'Tu paies une prime chaque mois, en général 2 à 4 % du loyer charges comprises. En échange, si le locataire cesse de payer, l\'assureur rembourse les loyers et charges impayés, jusqu\'à un plafond. L\'assureur examine le dossier du locataire (revenus, stabilité) et peut le refuser. La prime se déduit de tes revenus de loyers ; les remboursements, eux, sont imposables comme des loyers.',
    inGame: 'Prime de 3 % du loyer + charges, payée les mois où le bien est loué. Carence de 3 mois, remboursement dès le 2e mois d\'impayé (rétroactif), plafond de 70 000 €. Les locataires étudiants sont refusés (valeur de jeu). Simplifications : pas de franchise (l\'assureur rembourse dès le seuil atteint), pas de dossier à constituer, une seule formule.' },
  { id: 'gli-etudiants', category: 'location', term: 'Pourquoi l\'assurance refuse les étudiants',
    short: 'Un assureur n\'accepte un locataire que si son loyer pèse peu dans ses revenus et si sa situation est stable.',
    long: 'En général, le loyer ne doit pas dépasser environ un tiers des revenus du locataire, et il faut une situation professionnelle établie. Un étudiant, sans revenus stables, dépasse presque toujours ce seuil, sauf s\'il a un garant solide. Sans l\'accord de l\'assureur, pas de remboursement en cas d\'impayé : sur un studio d\'étudiant, le risque reste donc pour toi.',
    inGame: 'Règle simplifiée du jeu, non sourcée : tout locataire étudiant est refusé, sans exception. Les actifs et les familles sont acceptés.' },
  { id: 'carence', category: 'location', term: 'Délai de carence',
    short: 'La période après la souscription d\'une assurance pendant laquelle un incident n\'est pas couvert.',
    long: 'Si un impayé commence avant la fin du délai de carence, l\'assurance ne le rembourse pas, même plus tard. Il vaut donc mieux s\'assurer avant d\'en avoir besoin.',
    inGame: '3 mois pour l\'assurance loyers impayés ; il recommence si tu résilies puis te réassures.' },
  { id: 'treve-hivernale', category: 'location', term: 'Trêve hivernale',
    short: 'Du 1er novembre au 31 mars, un locataire ne peut pas être expulsé, même si le juge l\'a décidé.',
    long: 'La procédure continue et le locataire reste redevable de ses loyers, mais l\'expulsion est suspendue jusqu\'au 1er avril. Pour le propriétaire, cela peut allonger la période sans loyer de plusieurs mois. Forcer un locataire à partir pendant la trêve est un délit.',
    inGame: 'Si la procédure aboutit entre novembre et mars, le locataire reste jusqu\'en avril et ses impayés continuent de s\'accumuler (sauf remboursement par une assurance).' },
  { id: 'impaye', category: 'location', term: 'Loyer impayé',
    short: 'Un loyer que le locataire ne paie pas.',
    long: 'Un simple retard se rattrape souvent le mois suivant. Un impayé qui dure devient une procédure longue : dans le jeu, elle est raccourcie.' },

  // ── Les impôts
  { id: 'revenus-fonciers', category: 'impots', term: 'Revenus fonciers (régime réel)',
    short: 'Les loyers, moins ce que tu peux déduire, forment ce sur quoi tu paies l\'impôt.',
    long: 'On retire des loyers les charges déductibles, la taxe foncière et les intérêts du crédit. Si le résultat est négatif, tu ne paies rien ce mois-là.',
    inGame: 'Calculé par année civile, impôt réglé en décembre. Simplification pédagogique.' },
  { id: 'impot-loyers', category: 'impots', term: 'Impôt sur les loyers',
    short: 'Ton taux d\'impôt sur le revenu (ta « tranche ») plus les prélèvements sociaux, appliqués au résultat foncier.',
    long: 'Plus tes revenus sont élevés, plus cet impôt est élevé.' },
  { id: 'prelevements-sociaux', category: 'impots', term: 'Prélèvements sociaux',
    short: 'Des contributions qui financent la protection sociale, prélevées sur les revenus du patrimoine.',
    long: 'Ils s\'ajoutent à l\'impôt sur le revenu, sur les loyers comme sur les plus-values.',
    inGame: '17,2 % (taux 2026 à reconfirmer).' },
  { id: 'plus-value', category: 'impots', term: 'Plus-value immobilière',
    short: 'Le gain que tu réalises en revendant plus cher que tu n\'as acheté.',
    long: 'On compare le prix de vente avec le prix d\'achat, majoré des frais et travaux. Le gain est ensuite taxé, mais moins quand on garde le bien longtemps.' },
  { id: 'abattement', category: 'impots', term: 'Abattement pour durée de détention',
    short: 'Une remise sur la plus-value taxable, de plus en plus grande selon le nombre d\'années de détention.',
    long: 'Rien avant 5 ans, puis une réduction chaque année. Au bout de 22 ans, plus d\'impôt sur le revenu sur la plus-value ; au bout de 30 ans, plus aucun impôt. Le rythme n\'est pas le même pour l\'impôt sur le revenu et pour les prélèvements sociaux.' },
  { id: 'surtaxe', category: 'impots', term: 'Surtaxe sur les grosses plus-values',
    short: 'Un impôt supplémentaire quand la plus-value imposable dépasse 50 000 €.',
    long: 'Elle augmente par paliers avec le montant.',
    inGame: 'Le lissage entre les paliers est reconstitué et à reconfirmer.' },

  // ── La revente
  { id: 'ira', category: 'vente', term: 'Indemnité de remboursement anticipé',
    short: 'Une pénalité si tu rembourses ta banque avant la fin du prêt, par exemple en vendant.',
    long: 'Elle est plafonnée par la loi : six mois d\'intérêts ou un pourcentage du capital restant, le plus faible des deux.',
    inGame: 'Le plus petit entre 6 mois d\'intérêts et 3 % du capital restant.' },
  { id: 'frais-agence', category: 'vente', term: 'Frais d\'agence',
    short: 'La commission de l\'agent immobilier qui trouve l\'acheteur.',
    long: 'Ils sont libres et varient. Ils sont en général payés par le vendeur.',
    inGame: '5,78 % du prix de vente.' },
  { id: 'dpe', category: 'vente', term: 'DPE (diagnostic de performance énergétique)',
    short: 'Une note de A à G qui dit si le logement consomme peu ou beaucoup d\'énergie.',
    long: 'Les logements les plus mal notés sont progressivement interdits à la location : la note influence donc la valeur du bien et ce que tu peux en faire.',
    inGame: 'Location interdite : classe G depuis 2025, F depuis 2028, E depuis 2034.' },
  { id: 'audit-energetique', category: 'vente', term: 'Audit énergétique',
    short: 'Une étude plus poussée, obligatoire pour vendre certaines maisons mal classées.',
    long: 'Elle concerne les maisons et les immeubles entiers, pas les appartements en copropriété, et s\'est étendue progressivement aux classes F et G, puis E, et bientôt D.',
    inGame: 'Coût de jeu : 800 € (valeur de jeu, non sourcée).' },
  { id: 'decote', category: 'vente', term: 'Décote',
    short: 'Une baisse de prix quand on est obligé de vendre vite.',
    long: 'Un bien vendu en urgence ou aux enchères part souvent sous sa valeur.' },
  { id: 'vente-forcee', category: 'vente', term: 'Vente forcée (saisie)',
    short: 'La vente de ton bien imposée quand tu ne paies plus ton crédit.',
    long: 'Dans la réalité, c\'est une procédure judiciaire bien plus longue que dans le jeu (souvent plus d\'un an) : la banque doit d\'abord te mettre en demeure, puis un tribunal ordonne une vente aux enchères.',
    inGame: 'Alerte après 3 mois d\'impayés, vente à l\'amiable à −12 % proposée d\'abord, puis vente forcée à −25 % après 2 mois de grâce.' },

  // ── Dans le jeu
  { id: 'investcoin', category: 'jeu', term: 'InvestCoin (🪙)',
    short: 'La monnaie du jeu. Dans l\'Immobilier, 1 🪙 vaut 20 €.',
    long: 'Tous les achats, ventes et revenus sont convertis en pièces entières, avec un petit reliquat conservé pour ne rien perdre ni créer.' },
  { id: 'patrimoine-net', category: 'jeu', term: 'Patrimoine net (fonds propres)',
    short: 'La valeur de tes biens moins ce que tu dois à la banque.',
    long: 'C\'est ce qui t\'appartient vraiment. Il augmente quand tu rembourses le capital et quand les prix montent.' },
  { id: 'performance', category: 'jeu', term: 'Performance (classement)',
    short: 'Ton gain rapporté à l\'argent que tu as investi.',
    long: '(Fonds propres + argent encaissé − argent investi) ÷ argent investi. Un gain vendu reste un gain.' },
  { id: 'mode-accelere', category: 'jeu', term: 'Mode accéléré',
    short: 'Le temps passe quand tu le décides : un mois, un an…',
    long: 'Tu peux voir en quelques minutes ce qu\'un investissement donnerait sur de nombreuses années. Les événements aléatoires (départ d\'un locataire, travaux…) sont tirés de façon reproductible.' },
];

export const glossaryById = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));
