// Glossaire InvestKit — rédigé pour un débutant complet.
// Chaque entrée : id (utilisé par l'icône « ? »), terme, explication simple, et « Dans le jeu » quand le
// simulateur applique une règle précise. Les taux et seuils du jeu sont des simplifications pédagogiques.
export const GLOSSARY_CATEGORIES = {
  credit: 'Le crédit',
  achat: 'L\'achat',
  location: 'La location',
  impots: 'Les impôts',
  vente: 'La revente',
  bourse: 'Bourse et crypto',
  jeu: 'Dans le jeu',
  crypto: 'Crypto : le marché simulé',
};

export const GLOSSARY = [
  // ── Bourse et crypto
  { id: 'courtage', category: 'bourse', term: 'Courtage (frais d\'ordre)',
    short: 'Une petite commission payée à chaque achat et à chaque vente.',
    long: 'Le courtier qui passe tes ordres se rémunère en prenant un petit pourcentage du montant (avec un minimum). Les barèmes varient beaucoup d\'un courtier à l\'autre : compare-les avant d\'ouvrir un compte. Ces frais grignotent la performance : acheter et revendre sans arrêt coûte cher.',
    inGame: 'Les pièces payées en courtage disparaissent (elles ne sont données à personne). Taux : 0,5 % (actions), 0,35 % (ETF), 0,5 % (crypto), minimum 1 InvestCoin. Taux de jeu inspirés de courtiers réels, à reconfirmer.' },
  { id: 'pea', category: 'bourse', term: 'PEA (plan d\'épargne en actions)',
    short: 'Une enveloppe qui exonère d\'impôt sur le revenu les gains retirés après 5 ans.',
    long: 'Tu y loges des actions et des ETF européens. Si tu retires après 5 ans, tu ne paies plus d\'impôt sur le revenu sur les gains, seulement les prélèvements sociaux (18,6 % en 2026). Un retrait avant 5 ans entraîne en principe la clôture du plan (sauf cas particuliers), et les gains sont alors taxés à la flat tax. Les versements sont plafonnés à 150 000 €.',
    inGame: 'Le compteur des 5 ans démarre à ton premier achat en PEA. Simplifications : le PEA n\'est jamais clôturé et les prélèvements sociaux sont au taux de l\'année de la vente.' },
  { id: 'compte-titres', category: 'bourse', term: 'Compte-titres ordinaire (CTO)',
    short: 'L\'enveloppe sans avantage fiscal : chaque plus-value est taxée à la flat tax.',
    long: 'Aucune limite de montant ni de durée, mais tes gains sont imposés à chaque vente (flat tax : 12,8 % d\'impôt + prélèvements sociaux, soit 31,4 % en 2026).' },
  { id: 'flat-tax', category: 'bourse', term: 'Flat tax (prélèvement forfaitaire unique)',
    short: 'Un impôt à taux unique sur les plus-values : 12,8 % + prélèvements sociaux.',
    long: 'Depuis 2018, les gains sur titres et sur cryptomonnaies sont taxés à un taux fixe. Les prélèvements sociaux valent 18,6 % depuis 2026 (17,2 % auparavant) : le total est donc de 31,4 % (30 % auparavant).',
    inGame: 'Avant 2018, le jeu applique un taux simple de 19 % à la place du barème réel (simplification). Pas de report des moins-values.' },
  { id: 'impot-crypto', category: 'bourse', term: 'Impôt sur les cryptos',
    short: 'Tu ne paies un impôt que lorsque tu revends tes cryptos contre des euros.',
    long: 'Échanger une crypto contre une autre n\'est pas imposé ; seule la vente vers l\'euro (ou un achat avec tes cryptos) l\'est, à la flat tax. Si le total de tes ventes de l\'année ne dépasse pas 305 €, tu ne paies rien.',
    inGame: 'Toute vente de crypto se fait contre InvestCoins : elle est donc imposable. Le seuil de 305 InvestCoins est suivi année par année. Simplification : les gains des ventes déjà faites sous le seuil ne sont pas rattrapés.' },
  { id: 'action', category: 'bourse', term: 'Action',
    short: 'Une petite part d\'une entreprise. Si l\'entreprise vaut plus, ta part vaut plus.',
    long: 'En achetant une action, tu deviens copropriétaire d\'une entreprise cotée en Bourse. Son prix monte et descend selon les résultats de l\'entreprise et l\'humeur des investisseurs. Tu peux gagner, mais aussi perdre.',
    inGame: 'Tu achètes et vends avec tes InvestCoins, sur des cours annuels simplifiés (illustratifs, pas de vrais cours de Bourse), jusqu\'à ton année simulée.' },
  { id: 'etf', category: 'bourse', term: 'ETF (fonds indiciel)',
    short: 'Un « panier » d\'actions achetable en une seule fois, qui copie un grand indice.',
    long: 'Au lieu de choisir une entreprise, tu achètes un panier qui en contient des centaines. C\'est un moyen simple de répartir ton risque. Le prix du panier varie avec la moyenne des entreprises qu\'il contient.' },
  { id: 'obligation', category: 'bourse', term: 'Obligation',
    short: 'Un prêt que tu fais à un État ou à une entreprise, contre des intérêts.',
    long: 'Tu prêtes de l\'argent et on te le rend plus tard avec un intérêt. En général, c\'est moins risqué et moins rémunérateur que les actions.' },
  { id: 'crypto', category: 'bourse', term: 'Cryptomonnaie',
    short: 'Une monnaie numérique (Bitcoin, Ethereum…) dont le prix varie très fortement.',
    long: 'Il n\'y a ni entreprise ni État derrière : le prix ne dépend que de l\'offre et de la demande. Il peut doubler ou perdre la moitié de sa valeur en peu de temps. C\'est l\'actif le plus risqué du jeu.',
    inGame: 'Le crédit sur portefeuille est plus prudent en crypto (on te prête moins) car les prix bougent beaucoup.' },
  { id: 'volatilite', category: 'bourse', term: 'Volatilité',
    short: 'À quel point le prix monte et descend brutalement. Plus c\'est élevé, plus c\'est risqué.',
    long: 'Un actif peu volatil bouge doucement ; un actif très volatil peut gagner ou perdre beaucoup en peu de temps. Ce n\'est pas « mauvais » en soi, mais il faut pouvoir supporter les baisses.' },
  { id: 'diversification', category: 'bourse', term: 'Diversification',
    short: 'Ne pas mettre tous ses œufs dans le même panier.',
    long: 'En répartissant ton argent entre plusieurs actifs (actions, ETF, obligations, crypto), une mauvaise nouvelle sur l\'un d\'eux pèse moins sur l\'ensemble.' },
  { id: 'cours-cloture', category: 'bourse', term: 'Cours de clôture annuel',
    short: 'Le prix d\'un actif à la fin de l\'année. C\'est le seul prix que le jeu utilise.',
    long: 'Dans la vraie vie les prix changent à chaque seconde. Ici, pour simplifier, on ne connaît que le prix de fin d\'année : un actif a pu s\'effondrer en cours d\'année puis remonter sans que tu le voies.',
    inGame: 'Simplification pédagogique : les appels de marge et ventes forcées se calculent aussi sur ces prix annuels.' },
  { id: 'annee-simulee', category: 'bourse', term: 'Année simulée',
    short: 'L\'année du jeu où tu te trouves. Tu peux la faire avancer d\'un an à la fois.',
    long: 'Le temps ne passe pas tout seul : c\'est toi qui avances. Les prix changent alors pour de bon, tes intérêts éventuels sont payés, et tu vois si tes choix ont été bons.',
    inGame: 'Bourse et Crypto avancent par années ; l\'Immobilier avance par mois. Chaque domaine a sa propre horloge.' },
  { id: 'valeur-positions', category: 'bourse', term: 'Valeur des positions',
    short: 'Ce que valent, au prix du jour, tous les titres que tu détiens.',
    long: 'C\'est le nombre de titres multiplié par leur cours. Ce n\'est qu\'une valeur « sur le papier » tant que tu n\'as pas vendu.' },
  { id: 'performance-portefeuille', category: 'bourse', term: 'Performance du portefeuille',
    short: 'Ton gain ou ta perte en pourcentage depuis le départ.',
    long: 'Elle compare ce que tu possèdes maintenant (pièces + titres) à ce que tu avais au départ. Si tu as emprunté, le classement tient compte de la dette.',
    inGame: 'Classement en richesse nette de dettes, avec mention du levier utilisé.' },
  // ── Le crédit
  { id: 'credit', category: 'credit', term: 'Crédit immobilier',
    short: 'Un prêt de la banque pour acheter un bien, remboursé chaque mois pendant des années.',
    long: 'Tu empruntes une somme à la banque et tu la rends par petits morceaux (les mensualités), avec un supplément : les intérêts. Tant que le prêt n\'est pas fini, le bien sert de garantie à la banque.',
    inGame: 'Durée de 10 à 30 ans. La banque accepte ou refuse ton dossier et t\'explique pourquoi.' },
  { id: 'mensualite', category: 'credit', term: 'Mensualité',
    short: 'La somme que tu paies à la banque chaque mois.',
    long: 'Elle reste la même pendant tout le prêt. Elle contient trois choses : du capital remboursé, des intérêts et l\'assurance emprunteur.' },
  { id: 'capital-rembourse', category: 'credit', term: 'Capital remboursé',
    short: 'La part de ta mensualité qui diminue vraiment ta dette. Cet argent n\'est pas perdu : il t\'enrichit.',
    long: 'Chaque mois, une partie de la mensualité rembourse la somme empruntée. Ta dette baisse, donc la part du bien qui t\'appartient réellement augmente. Au début du prêt cette part est petite, elle grossit avec le temps.',
    inGame: 'Affiché séparément de l\'effort d\'épargne, car ce n\'est pas une dépense : c\'est de la richesse qui se construit.' },
  { id: 'interets', category: 'credit', term: 'Intérêts',
    short: 'Le prix que tu paies à la banque pour lui avoir emprunté de l\'argent.',
    long: 'Ils sont calculés sur ce qu\'il te reste à rembourser. Ils sont donc plus élevés au début du prêt. C\'est une vraie dépense, mais elle est déductible de tes revenus de loyers pour le calcul de l\'impôt.' },
  { id: 'taux', category: 'credit', term: 'Taux d\'intérêt',
    short: 'Le pourcentage que la banque te fait payer chaque année sur la somme empruntée.',
    long: 'Plus il est bas, moins le crédit coûte cher. Il change selon les années : un même bien peut être facile à financer une année et bien plus cher à financer une autre.',
    inGame: 'Le taux dépend de l\'année de jeu et de la durée choisie.' },
  { id: 'taeg', category: 'credit', term: 'TAEG',
    short: 'Le vrai coût du crédit en pourcentage : intérêts, assurance et frais compris.',
    long: 'Le taux annoncé ne dit pas tout. Le TAEG (taux annuel effectif global) ajoute l\'assurance et les frais de dossier. C\'est le chiffre à comparer entre deux offres.' },
  { id: 'assurance-emprunteur', category: 'credit', term: 'Assurance emprunteur',
    short: 'Une assurance qui rembourse la banque si tu ne peux plus payer (décès, invalidité).',
    long: 'Les banques l\'exigent presque toujours. Elle s\'ajoute à la mensualité.' },
  { id: 'apport', category: 'credit', term: 'Apport',
    short: 'L\'argent que tu mets de ta poche au départ, pour ne pas tout emprunter.',
    long: 'Plus l\'apport est élevé, moins tu empruntes, et plus la mensualité est légère. Les banques demandent en général au moins de quoi couvrir les frais de notaire.',
    inGame: 'Tu le paies en InvestCoins (1 InvestCoin = 1 €).' },
  { id: 'endettement', category: 'credit', term: 'Taux d\'endettement',
    short: 'La part de tes revenus qui part en remboursement de crédits.',
    long: 'La banque calcule : mensualités ÷ revenus. En France, les banques doivent en principe respecter un plafond de 35 % (assurance comprise) fixé par le Haut Conseil de stabilité financière, avec une petite marge de souplesse. Au-delà, elle refuse en général. Elle ne compte qu\'une partie des loyers que le bien rapportera, par prudence.' },
  { id: 'reste-a-vivre', category: 'credit', term: 'Reste à vivre',
    short: 'Ce qu\'il te reste chaque mois une fois le crédit et tes dépenses courantes payés.',
    long: 'Même si ton taux d\'endettement est correct, la banque vérifie qu\'il te reste assez pour vivre.' },
  { id: 'epargne-restante', category: 'credit', term: 'Épargne restante (en mensualités)',
    short: 'Ce qu\'il te reste en pièces à toi après un achat ou un prêt, comptées en nombre de mensualités.',
    long: 'Aucune loi n\'oblige à garder de l\'épargne après un achat, mais en vrai une banque regarde l\'épargne de précaution. Ici, le jeu t\'avertit si ce qu\'il te reste couvre moins de 3 mensualités : au-dessous, un loyer vide ou une dépense imprévue peut te mener à l\'impayé. C\'est un avertissement, jamais un refus. Les pièces d\'un prêt personnel non remboursé ne comptent pas comme de l\'épargne.',
    inGame: 'Avertissement non bloquant sur la fiche du bien, avant l\'achat, et dans la Banque. Seuil de 3 mensualités : valeur de jeu, non sourcée, à reconfirmer.' },
  { id: 'capital-restant', category: 'credit', term: 'Capital restant dû',
    short: 'Ce que tu dois encore à la banque à un instant donné.',
    long: 'Au début, il baisse lentement ; à la fin, plus vite. Quand tu vends, la banque récupère cette somme sur le prix de vente.' },
  { id: 'levier', category: 'credit', term: 'Effet de levier',
    short: 'Acheter un bien plus cher que ce que tu possèdes grâce au crédit.',
    long: 'Si le bien prend de la valeur, tu gagnes sur toute sa valeur alors que tu n\'as avancé qu\'une partie. Mais s\'il en perd, ou si les loyers ne suffisent pas, tu perds aussi plus : le levier agit dans les deux sens.' },

  // ── La banque
  { id: 'pret-personnel', category: 'credit', term: 'Prêt personnel',
    short: 'Un prêt sans garantie, plafonné selon tes revenus, à un taux plus élevé qu\'un prêt immobilier.',
    long: 'La banque ne prend pas ton bien en garantie : elle est donc plus prudente (montant limité) et plus chère (taux plus haut). Chaque mensualité compte dans ton taux d\'endettement, ce qui réduit ta capacité à emprunter pour acheter un bien.',
    inGame: 'Plafond : 6 mois de revenus nets de ton profil. Taux : taux de base de l\'année + 4,5 points (valeur de jeu). Réservé à l\'Immobilier. Un seul prêt à la fois.' },
  { id: 'credit-fleche', category: 'credit', term: 'Crédit fléché (prêt affecté)',
    short: 'Un prêt dont l\'argent ne peut servir qu\'à un usage précis.',
    long: 'Comme un prêt « affecté » réel : l\'argent est prévu pour un projet. Ici, seul le prêt sur portefeuille est fléché : ses pièces sont réservées à son domaine (Bourse ou Crypto) et ne peuvent pas être dépensées ailleurs. Le prêt personnel, lui, est libre comme dans la réalité, et le prêt immobilier reste attaché au bien (il ne crée aucune pièce libre). Cela évite qu\'un emprunt dans un domaine serve à jouer dans un autre où les pièces n\'ont pas la même valeur.',
    inGame: 'Les pièces réservées sont dépensées en premier dans leur domaine. Tes propres pièces restent libres partout.' },
  { id: 'taux-base', category: 'credit', term: 'Taux de base',
    short: 'Le taux de référence de l\'année, auquel la banque ajoute sa marge selon le risque.',
    long: 'Un prêt garanti par un bien coûte moins cher qu\'un prêt sans garantie : la banque ajoute une marge plus grande quand elle prend plus de risque.',
    inGame: 'Taux de base de jeu calé sur l\'histoire (valeur de jeu, non sourcée, à reconfirmer) + un écart par produit.' },
  { id: 'retablissement', category: 'credit', term: 'Procédure de rétablissement',
    short: 'Un dernier recours après un défaut : la dette du domaine est effacée, mais tout ce domaine repart de zéro.',
    long: 'Pour éviter qu\'un joueur reste bloqué pour toujours, il peut demander l\'effacement d\'une dette qu\'il ne peut pas payer. En contrepartie, il perd ce qu\'il avait dans ce domaine (titres ou biens), son rang, et il ne peut plus emprunter pendant un mois. Ce n\'est pas gratuit, ni illimité.',
    inGame: 'Au plus 3 procédures par compte, espacées de 30 jours (temps réel). Capital de base de 10 000 InvestCoins (le capital de départ) seulement si tu as moins. Les badges de domaine seront retirés quand ils seront rattachés au serveur.' },
  { id: 'pret-portefeuille', category: 'credit', term: 'Prêt sur portefeuille (Lombard)',
    short: 'Un prêt garanti par tes titres : tu empruntes en gardant tes actions ou ta crypto.',
    long: 'La banque te prête une partie de la valeur de tes titres (moins pour les actifs très volatils). Tu paies des intérêts, et ta garantie est réévaluée : si les cours baissent trop, la banque te demande d\'ajouter de la garantie ou de rembourser, sinon elle vend tes titres à ta place. Le levier augmente les gains, mais aussi les pertes.',
    inGame: 'Prêt maximum : 50 % de la valeur des actions, 30 % de la crypto. Taux variable = taux de base + 2 points (non sourcé). Intérêts payés à chaque passage d\'année. Un seul prêt par domaine.' },
  { id: 'appel-de-marge', category: 'credit', term: 'Appel de marge et vente forcée',
    short: 'Quand tes titres perdent trop de valeur, la banque exige de la garantie en plus, ou vend tes titres.',
    long: 'On compare la dette à la valeur des titres (le « rapport prêt/valeur »). Au-delà d\'un premier seuil, c\'est l\'appel de marge : tu dois rembourser une partie ou ajouter des titres. Au-delà d\'un second seuil, ou si tu ne fais rien, la banque vend une partie de tes titres, avec une décote, pour ramener la dette à un niveau sûr. Si la vente ne suffit pas, il te reste une dette.',
    inGame: 'Actions : appel à 65 %, vente forcée à 80 % (crypto : 39 % et 48 %). Simplification : les cours sont des clôtures annuelles, donc tout est évalué seulement au passage d\'une année ; dans la réalité, un krach en cours d\'année déclenche l\'appel tout de suite.' },
  { id: 'defaut-paiement', category: 'credit', term: 'Défaut de paiement',
    short: 'Quand tu ne rembourses plus ton prêt : la dette reste due et la banque ne te prête plus rien.',
    long: 'Une échéance manquée n\'efface pas la dette. Après plusieurs échéances impayées de suite, le prêt est déclaré en défaut : tu dois toujours l\'argent et tu ne peux plus emprunter tant qu\'il n\'est pas soldé.',
    inGame: '3 échéances impayées de suite = défaut. Le blocage se lève quand le prêt est soldé.' },
  { id: 'remboursement-anticipe', category: 'credit', term: 'Rembourser un prêt par anticipation',
    short: 'Solder un prêt avant la fin : tu économises des intérêts, mais la banque te fait payer une indemnité.',
    long: 'Plus il reste de temps, plus la banque perd d\'intérêts, donc plus l\'indemnité est élevée (dans la réglementation du crédit à la consommation, environ 1 % du capital si plus d\'un an reste, 0,5 % sinon).',
    inGame: 'Ces repères sont à reconfirmer sur les textes officiels.' },

  // ── L'achat
  { id: 'frais-notaire', category: 'achat', term: 'Frais de notaire',
    short: 'Les frais payés à l\'achat, surtout des taxes reversées à l\'État.',
    long: 'Le notaire authentifie la vente. La plus grande partie de ces frais sont des taxes. Ils sont plus élevés dans l\'ancien que dans le neuf.',
    inGame: 'Environ 7,5 % du prix dans l\'ancien, 2,5 % dans le neuf (simplification).' },
  { id: 'frais-dossier', category: 'achat', term: 'Frais de dossier',
    short: 'Ce que la banque facture pour monter ton prêt.',
    long: 'C\'est une petite somme payée une seule fois, au début.' },
  { id: 'expertise', category: 'achat', term: 'Expertise',
    short: 'Une visite d\'un professionnel qui repère les défauts cachés avant que tu achètes.',
    long: 'Une annonce ne dit pas tout : humidité, toiture, électricité… L\'expertise coûte un peu, mais peut t\'éviter une grosse surprise de travaux.' },
  { id: 'valeur-verte', category: 'achat', term: 'Valeur verte',
    short: 'Un logement économe en énergie se vend plus cher qu\'un logement mal classé.',
    long: 'Les études des notaires montrent que la note énergétique (DPE) pèse sur le prix : un appartement perd en moyenne environ 4 % par classe perdue (environ −12 % en classe G par rapport à D), et une maison environ 8 % par classe (environ −25 % en G, environ +17 % en A). Rénover pour gagner des classes peut donc faire monter la valeur du bien, en plus de permettre de le louer.',
    inGame: 'Effet sur les prix et la valeur, par rapport à la classe D. Les valeurs sourcées sont reprises (appartement G −12 %, maison G −25 %, maison A +17 %) ; les autres sont extrapolées (non sourcées, à reconfirmer). Le loyer a son propre effet énergie.' },
  { id: 'travaux', category: 'achat', term: 'Travaux',
    short: 'Les dépenses pour remettre un bien en état.',
    long: 'Les travaux annoncés sont dans l\'annonce. Ceux qui sont cachés apparaissent après l\'achat. Un bien à rénover est moins cher, mais te coûte du temps et de l\'argent.' },
  { id: 'bonne-affaire', category: 'achat', term: 'Vente pressée',
    short: 'Un vendeur qui doit vendre vite (succession, divorce, mutation) et accepte un prix plus bas.',
    long: 'Ces occasions existent dans la réalité. Un prix plus bas améliore le rendement, mais vérifie toujours l\'état du bien.' },

  // ── La location
  { id: 'cash-flow', category: 'location', term: 'Cash-flow',
    short: 'L\'argent qui entre moins l\'argent qui sort, chaque mois, pour un bien.',
    long: 'Loyers encaissés, moins charges, moins mensualité du crédit, moins impôts. S\'il est négatif, tu dois compléter de ta poche.' },
  { id: 'effort-epargne', category: 'location', term: 'Effort d\'épargne mensuel',
    short: 'Ce que tu dois ajouter chaque mois pour que le bien « tienne » quand les loyers ne suffisent pas.',
    long: 'Avec un crédit long, un cash-flow négatif est normal : la mensualité contient du capital remboursé, qui te constitue un patrimoine. L\'effort d\'épargne est donc une façon d\'épargner, à condition que le bien garde sa valeur et reste loué.',
    inGame: 'Calculé sur un mois normal, sans les événements exceptionnels (dépôt de garantie, travaux imprévus…).' },
  { id: 'loyer', category: 'location', term: 'Loyer',
    short: 'La somme que le locataire te paie chaque mois.',
    long: 'Il dépend de la ville, du quartier, de la taille, de l\'état et de la performance énergétique. Un loyer trop haut allonge le temps sans locataire.' },
  { id: 'rendement-brut', category: 'location', term: 'Rendement brut',
    short: 'Les loyers d\'une année divisés par le prix d\'achat.',
    long: 'C\'est un repère rapide pour comparer deux biens. Il ignore les charges, les impôts et le crédit ; le rendement réel est plus bas.' },
  { id: 'rendement-net', category: 'location', term: 'Pourquoi le net est plus bas que le brut',
    short: 'Le brut ne compte que le loyer. Le net retire ce qui sort : les mois sans locataire, les charges (taxe foncière, copropriété, entretien, assurance) et rapporte le tout aux frais d\'achat compris.',
    long: 'Le rendement brut est un repère rapide : loyers d\'une année divisés par le prix. Le rendement net est plus proche de la réalité : on retire la vacance (les mois sans locataire), toutes les charges du propriétaire, et on divise par le coût total (prix, frais de notaire, travaux annoncés). Le flux mensuel va plus loin : il retire aussi la mensualité du prêt. Un flux négatif veut dire que tu complètes chaque mois avec tes propres pièces. Plus les charges pèsent lourd par rapport au loyer, plus l\'écart entre brut et net est grand.',
    inGame: 'Sur chaque annonce, le net et le flux mensuel sont calculés avec l\'apport minimal exigé par la banque, un prêt sur 25 ans au taux de l\'année, assurance comprise : c\'est un repère, pas ta simulation d\'achat.' },
  { id: 'rendement-metropole', category: 'location', term: 'Pourquoi les grandes villes rapportent moins',
    short: 'Les métropoles chères ont des rendements plus faibles : le prix monte plus vite que les loyers.',
    long: 'Dans une grande ville très demandée, les logements sont chers mais les loyers ne le sont pas dans les mêmes proportions : le rendement brut tourne souvent autour de 3 à 5 %. En contrepartie, le logement se loue vite et son prix a tendance à tenir dans la durée. Dans une petite ville, le rendement est plus élevé, mais le risque de mois sans locataire ou de baisse de prix aussi. Quand les taux de crédit sont élevés, les métropoles s\'autofinancent très difficilement : c\'est réaliste, pas une erreur du jeu.',
    inGame: 'Marvelle (métropole) a volontairement un rendement faible ; Ternelle ou Brumevalle rapportent plus, avec plus de risque.' },
  { id: 'vacance', category: 'location', term: 'Vacance locative',
    short: 'Les mois où le logement est vide : pas de loyer, mais les charges continuent.',
    long: 'Elle est plus courte dans une ville où il y a beaucoup de demande (zone tendue) et plus longue dans une ville qui se vide. Baisser le loyer raccourcit la vacance.' },
  { id: 'zone-tendue', category: 'location', term: 'Zone tendue',
    short: 'Une zone où il y a bien plus de demandeurs de logements que de logements.',
    long: 'Les règles y sont différentes : par exemple le préavis du locataire y est d\'un mois au lieu de trois.' },
  { id: 'charges-recuperables', category: 'location', term: 'Charges récupérables',
    short: 'Des frais que tu avances mais que le locataire te rembourse (eau, entretien des parties communes…).',
    long: 'Elles n\'ont pas d\'effet sur ton résultat, sauf quand le logement est vide ou que le locataire ne paie pas.' },
  { id: 'charges-non-recuperables', category: 'location', term: 'Charges non récupérables',
    short: 'Les frais qui restent pour toi : taxe foncière, assurance du propriétaire, entretien, part de copropriété.',
    long: 'Elles pèsent sur ton cash-flow chaque année, que le bien soit loué ou non.' },
  { id: 'taxe-fonciere', category: 'location', term: 'Taxe foncière',
    short: 'Un impôt local que paie chaque année le propriétaire.',
    long: 'Elle dépend de la commune et de la taille du bien. Elle est déductible de tes revenus de loyers.' },
  { id: 'depot-garantie', category: 'location', term: 'Dépôt de garantie',
    short: 'Une somme versée par le locataire, gardée « en dépôt » pour couvrir d\'éventuels dégâts ou impayés.',
    long: 'Ce n\'est pas un revenu : tu dois le rendre en partant, moins les retenues justifiées (dégradations, loyers non payés).',
    inGame: 'Un mois de loyer. Il n\'est jamais compté dans ton cash-flow normal.' },
  { id: 'preavis', category: 'location', term: 'Préavis',
    short: 'Le délai entre l\'annonce du départ du locataire et son départ réel.',
    long: 'Pendant le préavis, le locataire paie son loyer.',
    inGame: 'Un mois en zone tendue ou pour certains motifs, trois mois sinon.' },
  { id: 'gli', category: 'location', term: 'Assurance loyers impayés (GLI)',
    short: 'Une assurance qui te rembourse les loyers que le locataire ne paie pas.',
    long: 'Tu paies une prime chaque mois, souvent de l\'ordre de 2 à 4 % du loyer charges comprises (ordre de grandeur indicatif, variable selon l\'assureur). En échange, si le locataire cesse de payer, l\'assureur rembourse les loyers et charges impayés, jusqu\'à un plafond. L\'assureur examine le dossier du locataire (revenus, stabilité) et peut le refuser. La prime se déduit de tes revenus de loyers ; les remboursements, eux, sont imposables comme des loyers.',
    inGame: 'Prime de 3 % du loyer + charges, payée les mois où le bien est loué. Carence de 3 mois, remboursement dès le 2e mois d\'impayé (rétroactif), plafond de 70 000 €. Les locataires étudiants sont refusés (valeur de jeu). Simplifications : pas de franchise (l\'assureur rembourse dès le seuil atteint), pas de dossier à constituer, une seule formule.' },
  { id: 'gli-etudiants', category: 'location', term: 'Pourquoi l\'assurance refuse les étudiants',
    short: 'Un assureur n\'accepte un locataire que si son loyer pèse peu dans ses revenus et si sa situation est stable.',
    long: 'En général, le loyer ne doit pas dépasser environ un tiers des revenus du locataire, et il faut une situation professionnelle établie. Un étudiant, sans revenus stables, dépasse presque toujours ce seuil, sauf s\'il a un garant solide. Sans l\'accord de l\'assureur, pas de remboursement en cas d\'impayé : sur un studio d\'étudiant, le risque reste donc pour toi.',
    inGame: 'Règle simplifiée du jeu, non sourcée : tout locataire étudiant est refusé, sans exception. Les actifs et les familles sont acceptés.' },
  { id: 'carence', category: 'location', term: 'Délai de carence',
    short: 'La période après la souscription d\'une assurance pendant laquelle un incident n\'est pas couvert.',
    long: 'Si un impayé commence avant la fin du délai de carence, l\'assurance ne le rembourse pas, même plus tard. Il vaut donc mieux s\'assurer avant d\'en avoir besoin.',
    inGame: '3 mois pour l\'assurance loyers impayés ; il recommence si tu résilies puis te réassures.' },
  { id: 'treve-hivernale', category: 'location', term: 'Trêve hivernale',
    short: 'Du 1er novembre au 31 mars, un locataire ne peut pas être expulsé, même si le juge l\'a décidé.',
    long: 'La procédure continue et le locataire reste redevable de ses loyers, mais l\'expulsion est suspendue jusqu\'au 1er avril. Pour le propriétaire, cela peut allonger la période sans loyer de plusieurs mois. Forcer un locataire à partir pendant la trêve est un délit.',
    inGame: 'Si la procédure aboutit entre novembre et mars, le locataire reste jusqu\'en avril et ses impayés continuent de s\'accumuler (sauf remboursement par une assurance).' },
  { id: 'impaye', category: 'location', term: 'Loyer impayé',
    short: 'Un loyer que le locataire ne paie pas.',
    long: 'Un simple retard se rattrape souvent le mois suivant. Un impayé qui dure devient une procédure longue : dans le jeu, elle est raccourcie.' },

  // ── Les impôts
  { id: 'revenus-fonciers', category: 'impots', term: 'Revenus fonciers (régime réel)',
    short: 'Les loyers, moins ce que tu peux déduire, forment ce sur quoi tu paies l\'impôt.',
    long: 'On retire des loyers les charges déductibles, la taxe foncière et les intérêts du crédit. Si le résultat est négatif, tu ne paies rien ce mois-là.',
    inGame: 'Calculé par année civile, impôt réglé en décembre. Simplification pédagogique.' },
  { id: 'impot-loyers', category: 'impots', term: 'Impôt sur les loyers',
    short: 'Ton taux d\'impôt sur le revenu (ta « tranche ») plus les prélèvements sociaux, appliqués au résultat foncier.',
    long: 'Plus tes revenus sont élevés, plus cet impôt est élevé.' },
  { id: 'prelevements-sociaux', category: 'impots', term: 'Prélèvements sociaux',
    short: 'Des contributions qui financent la protection sociale, prélevées sur les revenus du patrimoine.',
    long: 'Ils s\'ajoutent à l\'impôt sur le revenu, sur les loyers comme sur les plus-values. Pour les placements financiers (actions, PEA, crypto), le taux est de 18,6 % depuis 2026 ; pour les revenus fonciers et les plus-values immobilières, il reste de 17,2 %.',
    inGame: '17,2 % sur l\'immobilier ; 18,6 % sur la Bourse et la crypto (taux 2026, à reconfirmer sur un texte officiel).' },
  { id: 'plus-value', category: 'impots', term: 'Plus-value immobilière',
    short: 'Le gain que tu réalises en revendant plus cher que tu n\'as acheté.',
    long: 'On compare le prix de vente avec le prix d\'achat, majoré des frais et travaux. Le gain est ensuite taxé, mais moins quand on garde le bien longtemps.' },
  { id: 'abattement', category: 'impots', term: 'Abattement pour durée de détention',
    short: 'Une remise sur la plus-value taxable, de plus en plus grande selon le nombre d\'années de détention.',
    long: 'Rien avant 5 ans, puis une réduction chaque année. Au bout de 22 ans, plus d\'impôt sur le revenu sur la plus-value ; au bout de 30 ans, plus aucun impôt. Le rythme n\'est pas le même pour l\'impôt sur le revenu et pour les prélèvements sociaux.' },
  { id: 'surtaxe', category: 'impots', term: 'Surtaxe sur les grosses plus-values',
    short: 'Un impôt supplémentaire quand la plus-value imposable dépasse 50 000 €.',
    long: 'Elle augmente par paliers avec le montant.',
    inGame: 'Le lissage entre les paliers est reconstitué et à reconfirmer.' },

  // ── La revente
  { id: 'ira', category: 'vente', term: 'Indemnité de remboursement anticipé',
    short: 'Une pénalité si tu rembourses ta banque avant la fin du prêt, par exemple en vendant.',
    long: 'Elle est plafonnée par la loi : six mois d\'intérêts ou un pourcentage du capital restant, le plus faible des deux.',
    inGame: 'Le plus petit entre 6 mois d\'intérêts et 3 % du capital restant.' },
  { id: 'frais-agence', category: 'vente', term: 'Frais d\'agence',
    short: 'La commission de l\'agent immobilier qui trouve l\'acheteur.',
    long: 'Ils sont libres et varient. Ils sont en général payés par le vendeur.',
    inGame: '5,78 % du prix de vente.' },
  { id: 'dpe', category: 'vente', term: 'DPE (diagnostic de performance énergétique)',
    short: 'Une note de A à G qui dit si le logement consomme peu ou beaucoup d\'énergie.',
    long: 'Les logements les plus mal notés sont progressivement interdits à la location : la note influence donc la valeur du bien et ce que tu peux en faire.',
    inGame: 'Location interdite : classe G depuis 2025, F depuis 2028, E depuis 2034.' },
  { id: 'audit-energetique', category: 'vente', term: 'Audit énergétique',
    short: 'Une étude plus poussée, obligatoire pour vendre certaines maisons mal classées.',
    long: 'Elle concerne les maisons et les immeubles entiers, pas les appartements en copropriété, et s\'est étendue progressivement aux classes F et G, puis E, et bientôt D.',
    inGame: 'Coût de jeu : 800 € (valeur de jeu, non sourcée).' },
  { id: 'decote', category: 'vente', term: 'Décote',
    short: 'Une baisse de prix quand on est obligé de vendre vite.',
    long: 'Un bien vendu en urgence ou aux enchères part souvent sous sa valeur.' },
  { id: 'vente-forcee', category: 'vente', term: 'Vente forcée (saisie)',
    short: 'La vente de ton bien imposée quand tu ne paies plus ton crédit.',
    long: 'Dans la réalité, c\'est une procédure judiciaire bien plus longue que dans le jeu (souvent plus d\'un an) : la banque doit d\'abord te mettre en demeure, puis un tribunal ordonne une vente aux enchères.',
    inGame: 'Alerte après 3 mois d\'impayés, vente à l\'amiable à −12 % proposée d\'abord, puis vente forcée à −25 % après 2 mois de grâce.' },

  // ── Dans le jeu
  { id: 'investcoin', category: 'jeu', term: 'InvestCoin (InvestCoins)',
    short: 'La monnaie du jeu : 1 InvestCoin vaut 1 € de jeu, dans tous les domaines.',
    long: 'Tous les achats, ventes et revenus sont convertis en pièces entières, avec un petit reliquat conservé pour ne rien perdre ni créer. Les prix du jeu suivent les ordres de grandeur du marché, en InvestCoins, la monnaie du jeu.',
    inGame: 'Les InvestCoins n\'ont aucune valeur réelle : on ne peut ni les acheter, ni les retirer, ni les échanger entre joueurs.' },
  { id: 'patrimoine-net', category: 'jeu', term: 'Patrimoine net (fonds propres)',
    short: 'La valeur de tes biens moins ce que tu dois à la banque.',
    long: 'C\'est ce qui t\'appartient vraiment. Il augmente quand tu rembourses le capital et quand les prix montent.' },
  { id: 'performance', category: 'jeu', term: 'Performance (classement)',
    short: 'Ton gain rapporté à l\'argent que tu as investi.',
    long: '(Fonds propres + argent encaissé − argent investi) ÷ argent investi. Un gain vendu reste un gain.' },
  { id: 'mode-accelere', category: 'jeu', term: 'Mode accéléré',
    short: 'Le temps passe quand tu le décides : un mois, un an…',
    long: 'Tu peux voir en quelques minutes ce qu\'un investissement donnerait sur de nombreuses années. Les événements aléatoires (départ d\'un locataire, travaux…) sont tirés de façon reproductible.' },
  // ── Crypto : le marché simulé (rédigé pour ce projet ; chaque entrée renvoie vers le chapitre de quiz correspondant)
  { id: 'blockchain', category: 'crypto', term: 'Blockchain', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Un registre public où les opérations sont inscrites en blocs reliés les uns aux autres.',
    long: 'Chaque bloc contient des transactions et l\'empreinte du bloc précédent : modifier le passé obligerait à tout réécrire, ce qui est pratiquement impossible. Des milliers d\'ordinateurs conservent chacun une copie, donc personne ne peut effacer une opération tout seul.',
    inGame: 'Les cours que tu vois viennent de marchés qui échangent des actifs de plusieurs blockchains (Bitcoin, Ethereum…).' },
  { id: 'wallet', category: 'crypto', term: 'Portefeuille (wallet)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'L\'outil qui garde les clés permettant de dépenser tes cryptos.',
    long: 'Un portefeuille ne « contient » pas les cryptos : elles sont inscrites sur la blockchain, et le portefeuille garde les clés qui prouvent qu\'elles sont à toi. Il peut être un logiciel, une application ou un petit boîtier hors ligne. Laissées sur une plateforme, tes cryptos sont en fait gardées par elle.',
    inGame: 'Dans le jeu, tes positions sont gérées par le simulateur : pas de portefeuille à protéger, mais le risque de garde est rejoué dans le Journal du marché.' },
  { id: 'cle-privee', category: 'crypto', term: 'Clé privée et phrase de récupération', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Le secret qui donne le contrôle de tes cryptos : qui l\'a peut les dépenser.',
    long: 'La phrase de récupération (12 ou 24 mots) permet de retrouver ses clés si on perd son appareil. Ne la communique jamais, ne la photographie pas, ne la saisis sur aucun site : aucun service sérieux ne la demande. Si elle est perdue, personne ne peut la récupérer ; si elle est volée, les fonds partent sans recours.' },
  { id: 'frais-reseau', category: 'crypto', term: 'Frais de réseau (« gas »)', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Ce qu\'on paie au réseau pour qu\'il inscrive une transaction.',
    long: 'Ces frais rémunèrent ceux qui valident les transactions. Ils varient : quand beaucoup de monde veut transférer en même temps, ils montent. Ils s\'ajoutent aux frais de la plateforme quand tu envoies des cryptos vers un portefeuille.',
    inGame: 'Non simulés : dans le jeu, seuls les frais de plateforme, l\'écart achat/vente et le glissement sont payés.' },
  { id: 'stablecoin', category: 'crypto', term: 'Stablecoin', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Une crypto conçue pour valoir toujours à peu près 1 dollar.',
    long: 'Certains sont adossés à de vraies réserves (dollars, bons du Trésor), d\'autres à d\'autres cryptos, d\'autres à un simple algorithme. Stable ne veut pas sans risque : l\'émetteur peut mal gérer ses réserves, et le cours peut décrocher.',
    inGame: 'Les stablecoins du jeu sont dans le palier de liquidité le plus liquide ; leur décrochage (Terra en 2022, USDC en 2023) est rejoué dans le Journal.' },
  { id: 'depeg', category: 'crypto', term: 'Décrochage (« depeg »)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Quand un stablecoin s\'éloigne de 1 $ : il perd son ancrage.',
    long: 'Si les acheteurs doutent des réserves, tout le monde veut vendre en même temps et le cours s\'effondre sous 1 $. Le décrochage est parfois temporaire (USDC en mars 2023), parfois définitif (UST en 2022).' },
  { id: 'capitalisation', category: 'crypto', term: 'Capitalisation', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Le prix d\'une unité multiplié par le nombre d\'unités en circulation.',
    long: 'Elle mesure la taille d\'un actif, pas l\'argent réellement investi dedans : un petit volume d\'achats peut faire monter le prix d\'un actif dont peu d\'unités s\'échangent. Les plus grosses capitalisations sont en général plus liquides, mais pas à l\'abri d\'une chute.',
    inGame: 'Affichée dans le marché quand la donnée est importée.' },
  { id: 'volume', category: 'crypto', term: 'Volume d\'échanges', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Le montant échangé sur une période (ici sur 24 heures).',
    long: 'Un volume élevé signifie qu\'il y a beaucoup d\'acheteurs et de vendeurs : on peut entrer et sortir facilement. Un volume qui s\'effondre est un signal de désintérêt. Le volume est plus fiable que le prix pour juger si un marché est réellement vivant.',
    inGame: 'Sert à calculer le palier de liquidité et le glissement de tes ordres.' },
  { id: 'liquidite', category: 'crypto', term: 'Liquidité', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'La facilité à acheter ou vendre vite, sans faire bouger le prix.',
    long: 'Sur un actif très liquide, acheter 1 000 € ne change rien au cours. Sur un petit actif, le même ordre peut déplacer le prix de plusieurs pour cent, et en période de panique il peut devenir impossible de vendre au prix affiché.' },
  { id: 'palier-liquidite', category: 'crypto', term: 'Palier de liquidité (T1 à T4)', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Une note du jeu qui classe les actifs selon leur volume moyen.',
    long: 'T1 : plus de 500 millions de dollars échangés par jour en moyenne ; T2 : 50 M ; T3 : 5 M ; T4 : en dessous. Plus le palier est élevé (T4), plus les frais, l\'écart achat/vente et le glissement sont importants.',
    inGame: 'Frais de 0,10 % (T1) à 0,60 % (T4) ; écart de 0,02 % à 0,80 %. Valeurs de jeu, non sourcées, à reconfirmer.' },
  { id: 'ecart-achat-vente', category: 'crypto', term: 'Écart achat/vente (« spread »)', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'La différence entre le prix auquel on peut acheter et celui auquel on peut vendre.',
    long: 'On achète un peu plus cher que le prix « milieu » et on revend un peu moins cher : cet écart est un coût invisible à chaque aller-retour. Il est faible sur les grands actifs et plus large sur les petits, surtout en période agitée.',
    inGame: 'La moitié de l\'écart est appliquée à chaque exécution « au marché ». Il est multiplié par 3 pendant un épisode de volatilité extrême.' },
  { id: 'glissement', category: 'crypto', term: 'Glissement (« slippage »)', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Le prix moyen obtenu est moins bon que le prix affiché quand l\'ordre est gros.',
    long: 'Un gros ordre « mange » les offres les plus proches puis les suivantes, plus éloignées : le prix moyen se dégrade. Plus l\'ordre est gros par rapport à ce qui s\'échange d\'ordinaire, plus le glissement est fort.',
    inGame: '0,10 × racine carrée de (montant ÷ volume quotidien moyen), plafonné à 5 %. Valeur de jeu, non sourcée.' },
  { id: 'ordre-marche', category: 'crypto', term: 'Ordre au marché', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Acheter ou vendre tout de suite, au prix disponible.',
    long: 'C\'est simple et immédiat, mais tu ne maîtrises pas le prix exact : tu paies l\'écart achat/vente et le glissement. Dans un marché qui s\'affole, le prix obtenu peut être très différent de celui que tu voyais.',
    inGame: 'Exécuté côté serveur au dernier prix connu de ta date simulée ; jamais avec un prix envoyé par le navigateur.' },
  { id: 'ordre-limite', category: 'crypto', term: 'Ordre limite', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Acheter ou vendre seulement si le prix atteint un niveau que tu fixes.',
    long: 'Tu es sûr du prix, pas de l\'exécution : si le marché n\'atteint jamais ton niveau, rien ne se passe. Un ordre limite qui attend dans le carnet paie des frais réduits.',
    inGame: 'Évalué quand tu avances dans le temps, sur les bougies de la période ; frais divisés par deux, sans écart ni glissement.' },
  { id: 'stop-loss', category: 'crypto', term: 'Stop-loss', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Un ordre de vente qui se déclenche si le prix tombe sous un seuil, pour limiter une perte.',
    long: 'Il ne garantit pas le prix de vente : si le marché « saute » sous ton seuil (week-end, nouvelle brutale), la vente se fait au prix suivant, parfois bien plus bas. Un stop trop proche est déclenché par de simples variations normales.',
    inGame: 'Quand la bougie ouvre sous ton seuil, l\'exécution se fait à l\'ouverture (pas à ton seuil), en preneur de liquidité.' },
  { id: 'take-profit', category: 'crypto', term: 'Take-profit', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Un ordre de vente qui se déclenche quand le prix atteint un objectif de gain.',
    long: 'Il te fait sécuriser un gain sans surveiller l\'écran et évite de décider sous l\'euphorie. Contrepartie : si le prix continue de monter, tu n\'en profites plus.' },
  { id: 'liquidation', category: 'crypto', term: 'Liquidation', quiz: { domain: 'crypto_market', chapter: 4 },
    short: 'La vente forcée de tes actifs quand la garantie d\'un prêt ou d\'un effet de levier devient insuffisante.',
    long: 'Elle se déclenche automatiquement, souvent au pire moment, avec une décote : tu ne choisis ni le prix ni le moment. C\'est ainsi que des positions à effet de levier disparaissent en quelques heures lors d\'un krach.',
    inGame: 'Vente forcée quand la dette dépasse 80 % de la valeur de tes cryptos au plus bas de la période (décote de 3 %).' },
  { id: 'ltv', category: 'crypto', term: 'Ratio dette/garantie (LTV)', quiz: { domain: 'crypto_market', chapter: 4 },
    short: 'La dette divisée par la valeur de ce qui la garantit.',
    long: 'Si tu empruntes 3 000 en donnant 10 000 de cryptos en garantie, le ratio est de 30 %. Quand le prix des cryptos baisse, le ratio monte sans que tu aies rien fait.',
    inGame: 'Emprunt jusqu\'à 30 %, appel de marge à 65 %, vente forcée à 80 %.' },
  { id: 'risque-plateforme', category: 'crypto', term: 'Risque de plateforme (contrepartie)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Le risque que l\'entreprise qui garde tes actifs disparaisse, soit piratée ou bloque les retraits.',
    long: 'Mt. Gox (2014), Celsius et FTX (2022) ont montré que des clients peuvent perdre la totalité de leurs fonds alors que le cours de leur crypto n\'avait pas bougé. Ce risque s\'ajoute à celui du marché et ne se voit pas sur un graphique.',
    inGame: 'Rejoué par des événements du Journal du marché ; ne jamais tout laisser chez un seul acteur.' },
  { id: 'rug-pull', category: 'crypto', term: 'Escroquerie « rug pull » et jetons sans projet', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Quand les créateurs d\'un jeton vendent tout et disparaissent avec l\'argent des acheteurs.',
    long: 'Créer un jeton coûte presque rien ; il suffit d\'en faire la publicité, d\'attendre que le prix monte et de vendre. Un rendement « garanti » ou une hausse fulgurante sont des signaux d\'alerte.',
    inGame: 'Les actifs de risque 5 du catalogue ont souvent un historique court : perte totale possible.' },
  { id: 'defi', category: 'crypto', term: 'Finance décentralisée (DeFi)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Des services financiers (prêts, échanges) qui tournent par des programmes sur une blockchain, sans banque.',
    long: 'Les règles sont dans le code : c\'est transparent, mais un bug ou une faille peut coûter très cher et personne n\'est tenu de rembourser. Les rendements élevés proposés compensent un risque réel.' },
  { id: 'consensus', category: 'crypto', term: 'Preuve de travail et preuve d\'enjeu', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Les deux méthodes principales pour se mettre d\'accord sur l\'état de la blockchain.',
    long: 'Preuve de travail : des ordinateurs (les mineurs) font des calculs coûteux en électricité ; c\'est celle de Bitcoin. Preuve d\'enjeu : des validateurs immobilisent des cryptos en garantie ; c\'est celle d\'Ethereum depuis 2022 et elle consomme beaucoup moins d\'énergie.' },
  { id: 'halving', category: 'crypto', term: 'Halving du bitcoin', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Tous les quatre ans environ, la création de nouveaux bitcoins est divisée par deux.',
    long: 'Il est inscrit dans le protocole et connu des années à l\'avance : le marché l\'anticipe donc déjà. Son effet réel sur le prix est discuté.',
    inGame: 'Rejoué en mai 2020 et avril 2024 dans le Journal du marché.' },
  { id: 'fork', category: 'crypto', term: 'Fourche (« fork »)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Une modification des règles d\'une blockchain, parfois avec une scission en deux monnaies.',
    long: 'Quand la communauté ne s\'entend pas, la chaîne peut se scinder : c\'est arrivé pour Ethereum et Ethereum Classic en 2016, ou pour Bitcoin et Bitcoin Cash en 2017.' },
  { id: 'plus-haut-historique', category: 'crypto', term: 'Plus haut historique (ATH)', quiz: { domain: 'crypto_market', chapter: 1 },
    short: 'Le prix le plus élevé jamais atteint par un actif.',
    long: 'Il ne dit rien de ce qui arrivera ensuite : beaucoup d\'actifs n\'ont jamais retrouvé leur record. Acheter parce qu\'un actif « est au plus haut » ou parce qu\'il « est très loin de son plus haut » ne sont pas des raisons suffisantes.',
    inGame: 'Dans le jeu, plus haut et plus bas sont calculés seulement sur les données connues à ta date simulée.' },
  { id: 'drawdown', category: 'crypto', term: 'Baisse depuis un sommet (« drawdown »)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'La perte entre le plus haut et le point bas suivant.',
    long: 'Les grandes cryptos ont déjà perdu 70 à 85 % de leur valeur (2014, 2018, 2022). Se demander « quelle baisse puis-je supporter ? » avant d\'acheter est plus utile que de chercher le bon moment.' },
  { id: 'correlation', category: 'crypto', term: 'Corrélation', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'À quel point deux actifs montent et baissent en même temps.',
    long: 'Pendant les crises (mars 2020, 2022), les cryptos ont beaucoup suivi les actions technologiques : ce que l\'on croyait indépendant baissait ensemble. Répartir son argent entre dix cryptos diversifie peu si elles baissent toutes en même temps.',
    inGame: 'Illustrée par les événements de mars 2020 et de la hausse des taux de 2022.' },
  { id: 'bougie', category: 'crypto', term: 'Bougie japonaise', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Une barre qui résume un prix sur une période : ouverture, plus haut, plus bas, clôture.',
    long: 'Le corps va de l\'ouverture à la clôture (vert si ça monte, rouge si ça baisse) et les mèches montrent les extrêmes. Une bougie journalière résume 24 heures ; une bougie « en cours » n\'est pas terminée.',
    inGame: 'Les bougies plus longues (4 h, semaine, mois) sont recalculées à partir de bougies terminées à ta date simulée.' },
  { id: 'echelle-log', category: 'crypto', term: 'Échelle logarithmique', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Un axe des prix où une même variation en pourcentage occupe la même hauteur.',
    long: 'Sur une échelle normale, passer de 10 à 20 paraît petit à côté de 100 à 200. En logarithmique, les deux sont un doublement, donc de même hauteur : c\'est la bonne échelle pour comparer de longues périodes.' },
  { id: 'base-100', category: 'crypto', term: 'Comparaison en base 100', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Ramener plusieurs actifs à 100 au départ pour comparer leur évolution.',
    long: 'On compare des pourcentages, pas des prix : un actif à 50 000 $ et un autre à 0,5 $ deviennent comparables. La base 100 est la première date commune aux actifs choisis.' },
  { id: 'moyenne-mobile', category: 'crypto', term: 'Moyennes mobiles (SMA, EMA)', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'La moyenne des derniers prix, pour lisser les variations.',
    long: 'La SMA donne le même poids à chaque jour ; l\'EMA donne plus de poids aux jours récents. Un prix qui passe au-dessus de sa moyenne est souvent lu comme une tendance à la hausse, mais c\'est un outil de lecture, pas une prédiction.' },
  { id: 'bollinger', category: 'crypto', term: 'Bandes de Bollinger', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Une enveloppe autour d\'une moyenne mobile, à ± 2 écarts-types.',
    long: 'Elle s\'élargit quand le marché s\'agite et se resserre quand il est calme. Un prix qui touche une bande n\'annonce pas un retournement : en tendance forte, il peut « longer » la bande longtemps.' },
  { id: 'rsi', category: 'crypto', term: 'RSI', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Un indicateur de 0 à 100 qui compare les hausses et les baisses récentes.',
    long: 'Au-dessus de 70, on parle souvent de « surachat », sous 30 de « survente » ; mais un actif peut rester très longtemps au-dessus de 70 pendant une envolée. Il décrit le passé récent, il ne dit pas ce qui va suivre.' },
  { id: 'macd', category: 'crypto', term: 'MACD', quiz: { domain: 'crypto_market', chapter: 5 },
    short: 'Un indicateur qui compare une moyenne mobile rapide et une lente.',
    long: 'La ligne MACD est la différence entre deux moyennes (12 et 26 jours par défaut), comparée à sa propre moyenne (9 jours). Quand elle croise sa moyenne, certains y voient un changement de dynamique ; les faux signaux sont fréquents.' },
  { id: 'echange-crypto', category: 'crypto', term: 'Échange crypto contre crypto', quiz: { domain: 'crypto_market', chapter: 3 },
    short: 'Échanger une crypto contre une autre, sans repasser par les euros.',
    long: 'En France, un tel échange n\'est pas imposé au moment où il est fait : l\'impôt n\'intervient qu\'à la vente contre euros (au-delà d\'un seuil annuel de 305 € de cessions). Le prix d\'achat d\'origine est conservé. Les taux exacts sont à vérifier sur service-public.fr.',
    inGame: 'Échange sans impôt, seuls les frais sont payés ; le prix de revient est reporté sur l\'actif reçu. Taux et seuil de jeu, à reconfirmer.' },
  { id: 'ico', category: 'crypto', term: 'Offre initiale de jetons (ICO)', quiz: { domain: 'crypto_market', chapter: 2 },
    short: 'Une levée de fonds où un projet vend ses propres jetons au public.',
    long: 'En 2017, des milliers d\'ICO ont levé des fonds sur de simples promesses ; beaucoup n\'ont jamais livré de produit. Un projet sérieux doit avoir un produit, des utilisateurs et une équipe identifiable.',
    inGame: 'La Chine a interdit les ICO en septembre 2017 (événement du Journal).' },
];

export const glossaryById = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));
