// Exemples concrets et « à ne pas confondre avec » : location, impôts, revente, crypto.
// Mêmes règles que glossaireFichesA.js. Chiffres ronds et inventés pour comprendre.
export const FICHES_B = {
  // Location
  "cash-flow": { ex: "Loyer 700 €, mensualité 550 €, charges et impôts 100 € : ton cash-flow est de +50 € par mois.",
    vs: [['effort-epargne', "L'effort d'épargne est un cash-flow négatif que tu combles de ta poche."], ['rendement-brut', "Le rendement oublie le crédit, le cash-flow non."]] },
  "effort-epargne": { ex: "Loyer 600 €, tout le reste coûte 800 € : tu mets 200 € de ta poche chaque mois.",
    vs: [['cash-flow', "Le cash-flow peut être positif ; l'effort d'épargne est son contraire."], ['apport', "L'apport est versé une fois au début."]] },
  loyer: { ex: "Tu loues 40 m² à 15 € le m² : le loyer est de 600 € par mois.",
    vs: [['mensualite', "La mensualité est ce que tu paies à la banque."], ['charges-recuperables', "Les charges récupérables s'ajoutent au loyer sans être un revenu."]] },
  "rendement-brut": { ex: "Un bien à 100 000 € qui rapporte 6 000 € de loyers par an a un rendement brut de 6 %.",
    vs: [['cash-flow', "Le rendement brut oublie crédit, charges et impôts."], ['rendement-metropole', "Le rendement est plus faible dans les grandes villes, où les prix sont plus hauts."]] },
  "rendement-net": { ex: "Un bien à 100 000 € loué 6 000 € par an affiche 6 % brut. Après 600 € de vacance et 1 500 € de charges, il reste 3 900 € : environ 3,6 % net sur un coût total de 107 500 € avec les frais de notaire.",
    vs: [['rendement-brut', "Le brut ne compte que le loyer ; le net retire vacance, charges et frais d'achat."], ['cash-flow', "Le flux mensuel retire en plus la mensualité du prêt."]] },
  "rendement-metropole": { ex: "À Paris, un bien se paie très cher pour un loyer qui ne suit pas : le rendement brut y est souvent plus bas qu'en petite ville.",
    vs: [['rendement-brut', "Le rendement brut est le calcul ; ici, on explique pourquoi il varie."]] },
  vacance: { ex: "Si ton bien reste vide 2 mois sur 12, tu perds 2 loyers : le rendement réel baisse d'un sixième.",
    vs: [['impaye', "Dans la vacance, le logement est vide ; dans l'impayé, il est occupé mais non payé."], ['preavis', "Pendant le préavis, le loyer est encore payé."]] },
  "zone-tendue": { ex: "Dans une grande ville où les logements manquent, un bien se reloue vite : la vacance est faible, mais les règles du bail sont plus strictes.",
    vs: [['vacance', "Une zone tendue réduit la vacance, elle ne la supprime pas."]] },
  "charges-recuperables": { ex: "L'entretien de l'ascenseur est avancé par toi puis refacturé au locataire : tu le récupères.",
    vs: [['charges-non-recuperables', "Les non récupérables restent à ta charge."], ['loyer', "Ce n'est pas un loyer supplémentaire : tu ne gagnes rien dessus."]] },
  "charges-non-recuperables": { ex: "La taxe foncière et l'assurance du bien sont payées par toi, sans les refacturer.",
    vs: [['charges-recuperables', "Les charges récupérables sont remboursées par le locataire."], ['taxe-fonciere', "La taxe foncière en est l'exemple le plus connu."]] },
  "taxe-fonciere": { ex: "Pour un petit appartement, la taxe foncière peut atteindre un mois de loyer par an, selon la commune.",
    vs: [['charges-non-recuperables', "Elle fait partie des charges que le locataire ne rembourse pas."], ['impot-loyers', "Elle se déduit de tes loyers avant l'impôt, mais elle n'est pas cet impôt."]] },
  "depot-garantie": { ex: "Le locataire verse 600 € à l'entrée ; en partant, tu lui rends 600 € moins les dégâts éventuels.",
    vs: [['loyer', "Ce n'est pas un revenu : tu dois le rendre."], ['preavis', "Le préavis est un délai, pas une somme."]] },
  preavis: { ex: "Le locataire annonce son départ : tu continues à toucher le loyer pendant le préavis, puis le logement se libère.",
    vs: [['vacance', "La vacance commence après le départ."], ['treve-hivernale', "La trêve est un blocage d'expulsion, pas un délai de départ."]] },
  gli: { ex: "Tu paies 20 € par mois ; si le locataire arrête de payer, l'assureur te verse les loyers manquants après le délai prévu.",
    vs: [['assurance-emprunteur', "L'assurance emprunteur couvre ton crédit, la GLI couvre les loyers."], ['carence', "La carence est le délai avant que la GLI paie."]] },
  "gli-etudiants": { ex: "Un étudiant sans revenu stable est refusé par l'assureur : pour un tel locataire, le propriétaire demande souvent un garant.",
    vs: [['gli', "C'est la GLI elle-même ; cette fiche explique son refus."]] },
  carence: { ex: "Ta GLI a une carence de 3 mois : si le loyer manque dès le premier mois, tu n'es pas remboursé tout de suite.",
    vs: [['preavis', "Le préavis est du côté du locataire."], ['gli', "La GLI paie après la carence."]] },
  "treve-hivernale": { ex: "Un jugement ordonne l'expulsion en décembre : elle ne peut avoir lieu qu'à partir du 1er avril.",
    vs: [['impaye', "L'impayé est le problème ; la trêve est un frein à l'expulsion."], ['preavis', "Le préavis est un départ volontaire."]] },
  impaye: { ex: "Ton locataire ne paie pas son loyer de 600 € pendant 3 mois : 1 800 € sont dus.",
    vs: [['vacance', "Un logement vide ne coûte rien en impayés."], ['defaut-paiement', "Le défaut est celui de l'emprunteur, pas du locataire."]] },

  // Impôts
  "revenus-fonciers": { ex: "Loyers 7 000 €, charges déductibles 1 000 €, intérêts d'emprunt 2 000 € : tu es imposé sur 4 000 €.",
    vs: [['cash-flow', "Le cash-flow compte le capital remboursé, l'impôt non."], ['impot-loyers', "L'impôt est calculé à partir de ce résultat."]] },
  "impot-loyers": { ex: "Avec 4 000 € de résultat foncier et une tranche à 11 %, plus 17,2 % de prélèvements sociaux : environ 1 128 € d'impôt.",
    vs: [['flat-tax', "La flat tax ne s'applique pas aux loyers."], ['prelevements-sociaux', "Les prélèvements sociaux s'ajoutent à l'impôt."]] },
  "prelevements-sociaux": { ex: "Sur 1 000 € de loyers imposables, 17,2 % de prélèvements sociaux font 172 €, en plus de l'impôt sur le revenu.",
    vs: [['flat-tax', "La flat tax contient les prélèvements sociaux mais aussi 12,8 % d'impôt."]] },
  "plus-value": { ex: "Tu as acheté 150 000 € et revendu 200 000 € : la plus-value de 50 000 € est taxée, mais moins si tu as gardé le bien longtemps.",
    vs: [['abattement', "L'abattement la réduit avec les années."], ['surtaxe', "La surtaxe s'ajoute si elle est très grosse."]] },
  abattement: { ex: "Après 15 ans de détention, une partie de ta plus-value n'est plus taxée ; après 22 ans, plus d'impôt sur le revenu.",
    vs: [['surtaxe', "L'abattement baisse l'impôt, la surtaxe le fait monter."], ['decote', "La décote est un rabais sur le prix, pas sur l'impôt."]] },
  surtaxe: { ex: "Pour une plus-value nette de 80 000 €, une taxe supplémentaire s'ajoute à l'impôt habituel.",
    vs: [['plus-value', "C'est un supplément sur la plus-value, pas l'impôt de base."]] },

  // Revente
  ira: { ex: "Tu vends et rembourses 100 000 € : l'IRA est limitée à six mois d'intérêts ou 3 % du capital restant, soit 3 000 € maximum.",
    vs: [['remboursement-anticipe', "Le remboursement anticipé est l'acte ; l'IRA est le coût."], ['frais-dossier', "Les frais de dossier se paient à l'ouverture."]] },
  "frais-agence": { ex: "Pour un bien vendu 200 000 € avec 5 % de frais d'agence : 10 000 € sont payés à l'agence.",
    vs: [['frais-notaire', "Le notaire est payé pour l'acte, pas pour trouver l'acheteur."]] },
  dpe: { ex: "Deux logements identiques : l'un en B, l'autre en G. Le second risque d'être interdit à la location et de se vendre moins cher.",
    vs: [['audit-energetique', "L'audit va plus loin que la simple note."], ['valeur-verte', "La valeur verte est l'effet de la note sur le prix."]] },
  "audit-energetique": { ex: "Tu vends une maison classée F : un audit énergétique propose des travaux chiffrés avant la vente.",
    vs: [['dpe', "Le DPE donne une note ; l'audit propose un plan de travaux."]] },
  decote: { ex: "Un bien estimé 200 000 € vendu 180 000 € dans l'urgence : la décote est de 10 %.",
    vs: [['abattement', "L'abattement concerne l'impôt, pas le prix."], ['vente-forcee', "La vente forcée implique souvent une décote plus forte."]] },
  "vente-forcee": { ex: "Après des impayés prolongés, la banque obtient la vente du bien aux enchères, souvent bien en dessous de sa valeur.",
    vs: [['bonne-affaire', "La vente pressée est choisie par le vendeur."], ['decote', "La décote est la perte de prix qui en résulte."]] },

  // Crypto
  blockchain: { ex: "Un registre partagé où chaque transaction est ajoutée en bloc : les blocs s'enchaînent et personne ne peut les réécrire facilement.",
    vs: [['crypto', "La crypto est la monnaie ; la blockchain est le registre."], ['wallet', "Le portefeuille donne accès à la blockchain, il ne la contient pas."]] },
  wallet: { ex: "Une application qui garde tes clés et te permet d'envoyer ou de recevoir des cryptos.",
    vs: [['cle-privee', "La clé est ce qui protège le portefeuille."], ['risque-plateforme', "Un portefeuille sur une plateforme dépend d'elle."]] },
  "cle-privee": { ex: "Une phrase de 12 ou 24 mots : qui la possède contrôle tes cryptos. Ne la donne à personne.",
    vs: [['wallet', "Le portefeuille est l'outil ; la clé est son secret."]] },
  "frais-reseau": { ex: "Envoyer une crypto peut coûter 1 € un jour calme et 20 € quand le réseau est saturé.",
    vs: [['courtage', "Le courtage paie le courtier, les frais de réseau paient le réseau."], ['glissement', "Le glissement vient du manque d'acheteurs, pas du réseau."]] },
  stablecoin: { ex: "Un jeton qui vise 1 € : tu peux t'en servir pour mettre ton argent « à l'abri » entre deux achats.",
    vs: [['crypto', "Les autres cryptos varient fortement."], ['depeg', "Un stablecoin peut décrocher de son prix cible."]] },
  depeg: { ex: "Un stablecoin cote 0,92 € au lieu de 1 € : il a décroché, c'est un signe de risque.",
    vs: [['stablecoin', "Le stablecoin est censé rester stable ; le depeg est son échec."]] },
  capitalisation: { ex: "Un jeton à 2 € avec 1 million d'unités en circulation vaut 2 millions d'euros en capitalisation.",
    vs: [['volume', "Le volume mesure les échanges ; la capitalisation mesure la taille."], ['liquidite', "Une grosse capitalisation ne garantit pas de pouvoir vendre facilement."]] },
  volume: { ex: "Si 10 millions d'euros d'une crypto s'échangent en 24 h, c'est son volume sur la journée.",
    vs: [['capitalisation', "La capitalisation est une valeur ; le volume est une activité."], ['liquidite', "Un fort volume aide la liquidité."]] },
  liquidite: { ex: "Vendre 100 € d'une crypto très échangée est immédiat ; vendre 100 000 € d'un jeton rare peut faire chuter son prix.",
    vs: [['volume', "Le volume décrit les échanges passés."], ['palier-liquidite', "Le palier classe une crypto selon sa liquidité."]] },
  "palier-liquidite": { ex: "Un jeton du palier T1 a de faibles frais ; au palier T4, les écarts et le glissement sont bien plus grands.",
    vs: [['liquidite', "La liquidité est la notion ; le palier est le classement du jeu."]] },
  "ecart-achat-vente": { ex: "Une crypto s'achète 100,50 € et se vend 99,50 € : l'écart de 1 € est un coût caché.",
    vs: [['glissement', "L'écart est fixe pour un petit ordre ; le glissement apparaît avec les gros ordres."], ['courtage', "Le courtage est une commission annoncée, l'écart est caché."]] },
  glissement: { ex: "Tu veux acheter pour 10 000 € mais il y a peu de vendeurs : ton prix moyen finit à 1 % au-dessus du prix affiché.",
    vs: [['ecart-achat-vente', "L'écart existe aussi pour un petit ordre."], ['liquidite', "Le glissement est un symptôme d'une liquidité faible."]] },
  "ordre-marche": { ex: "Tu cliques sur « acheter » : l'ordre est exécuté tout de suite au meilleur prix disponible.",
    vs: [['ordre-limite', "L'ordre limite attend que ton prix soit atteint."]] },
  "ordre-limite": { ex: "Tu fixes 90 € pour acheter alors que l'actif cote 100 € : l'ordre ne s'exécute que s'il descend à 90 €.",
    vs: [['ordre-marche', "L'ordre au marché passe tout de suite, sans choix du prix."], ['stop-loss', "Le stop-loss déclenche une vente quand le prix baisse."]] },
  "stop-loss": { ex: "Tu as acheté à 100 € et tu fixes un stop à 90 € : si le prix descend à 90 €, la vente se déclenche pour limiter la perte.",
    vs: [['take-profit', "Le take-profit vend pour encaisser un gain."], ['liquidation', "La liquidation est imposée, le stop-loss est choisi par toi."]] },
  "take-profit": { ex: "Tu as acheté à 100 € et tu fixes 120 € : la vente se déclenche automatiquement pour sécuriser ton gain.",
    vs: [['stop-loss', "Le stop-loss protège contre une perte."], ['ordre-limite', "Un take-profit est une sorte d'ordre limite de vente."]] },
  liquidation: { ex: "Avec un prêt adossé à ton portefeuille, une chute de prix force la vente de tes cryptos pour rembourser.",
    vs: [['stop-loss', "Le stop-loss est ta décision ; la liquidation est subie."], ['appel-de-marge', "L'appel de marge précède la liquidation."]] },
  ltv: { ex: "Tu empruntes 4 000 € contre 10 000 € de garantie : le LTV est de 40 %. S'il monte trop, tu risques la liquidation.",
    vs: [['endettement', "L'endettement compare dette et revenus, le LTV dette et garantie."]] },
  "risque-plateforme": { ex: "Si la plateforme où tu gardes tes cryptos fait faillite, tu peux tout perdre même si les cours étaient bons.",
    vs: [['wallet', "Un portefeuille personnel supprime ce risque mais augmente ta responsabilité."], ['rug-pull', "Le rug pull est une escroquerie, pas une faillite."]] },
  "rug-pull": { ex: "Un jeton inconnu monte de 300 % en une semaine puis son créateur retire l'argent et disparaît : le prix tombe à zéro.",
    vs: [['risque-plateforme', "La plateforme qui fait faillite n'est pas forcément malhonnête."], ['ico', "Une offre initiale n'est pas forcément une escroquerie."]] },
  defi: { ex: "Un service où l'on prête ou échange des cryptos par des programmes automatiques, sans banque ni courtier.",
    vs: [['risque-plateforme', "En DeFi, c'est un programme qui porte le risque."], ['blockchain', "La blockchain en est le support."]] },
  consensus: { ex: "Le bitcoin utilise la preuve de travail (des ordinateurs qui résolvent des calculs) ; d'autres réseaux utilisent la preuve d'enjeu.",
    vs: [['blockchain', "La blockchain est le registre, le consensus est la façon de l'ajouter."]] },
  halving: { ex: "Tous les 4 ans environ, la récompense des mineurs de bitcoin est divisée par deux : de nouvelles pièces arrivent moins vite.",
    vs: [['fork', "Un fork change les règles, le halving est prévu depuis le début."]] },
  fork: { ex: "Une partie de la communauté refuse une mise à jour : le réseau se scinde en deux versions.",
    vs: [['halving', "Le halving est un événement programmé, sans scission."]] },
  "plus-haut-historique": { ex: "Une crypto atteint 70 000 € : tant qu'elle ne dépasse pas ce prix, c'est son plus haut historique.",
    vs: [['drawdown', "Le drawdown mesure la distance au plus haut."]] },
  drawdown: { ex: "Un portefeuille passe de 10 000 € à 7 000 € : le drawdown est de −30 %.",
    vs: [['volatilite', "La volatilité décrit l'agitation, le drawdown décrit la chute."], ['plus-haut-historique', "Le plus haut est le point de départ du drawdown."]] },
  correlation: { ex: "Deux cryptos qui montent et baissent presque toujours ensemble sont très corrélées : en détenir deux n'aide guère.",
    vs: [['diversification', "La diversification cherche des actifs peu corrélés."]] },
  bougie: { ex: "Une bougie verte résume une journée : le prix a ouvert à 100 €, a touché 105 € puis 98 €, et a fini à 103 €.",
    vs: [['cours-cloture', "La clôture n'est qu'un des quatre prix d'une bougie."]] },
  "echelle-log": { ex: "Sur une échelle logarithmique, passer de 10 à 20 € a la même hauteur que de 100 à 200 € : on compare des pourcentages.",
    vs: [['base-100', "La base 100 compare des courbes entre elles, l'échelle log change l'axe."]] },
  "base-100": { ex: "Deux actifs démarrent à 100 : après un an, l'un est à 150 et l'autre à 80. On voit tout de suite lequel a le mieux fait.",
    vs: [['echelle-log', "L'échelle log change l'axe, la base 100 change le point de départ."]] },
  "moyenne-mobile": { ex: "La moyenne mobile sur 20 jours lisse le prix : quand le cours passe au-dessus, certains y voient un signal de hausse.",
    vs: [['bollinger', "Les bandes de Bollinger entourent la moyenne mobile."], ['rsi', "Le RSI mesure la vitesse du prix, pas sa moyenne."]] },
  bollinger: { ex: "Deux bandes encadrent le prix autour de sa moyenne : un prix qui touche la bande haute est « tendu » sans prédire une baisse.",
    vs: [['moyenne-mobile', "La moyenne mobile est la ligne centrale."]] },
  rsi: { ex: "Un RSI au-dessus de 70 est lu comme « suracheté », en dessous de 30 comme « survendu » : c'est une aide, pas une certitude.",
    vs: [['macd', "Le MACD compare deux moyennes, le RSI compare hausses et baisses."]] },
  macd: { ex: "Quand la ligne du MACD croise sa ligne de signal vers le haut, certains y voient un signal d'achat.",
    vs: [['rsi', "Le RSI se lit entre 0 et 100, le MACD n'a pas de bornes."], ['moyenne-mobile', "Le MACD est construit à partir de moyennes mobiles."]] },
  "echange-crypto": { ex: "Tu transformes du bitcoin en ethereum : en France, il n'y a pas d'impôt à cet instant-là.",
    vs: [['impot-crypto', "L'impôt se déclenche à la vente contre des euros."]] },
  ico: { ex: "Un projet vend des jetons avant de les lancer : tu achètes sur la promesse d'un projet qui n'existe parfois pas encore.",
    vs: [['rug-pull', "Certaines offres sont honnêtes, d'autres sont des escroqueries."], ['action', "Un jeton n'est pas une part de société."]] },
};
