// Glossaire InvestKit — rédigé pour un débutant complet.
// Chaque entrée : id (utilisé par l'icône « ? »), terme, explication simple, et « Dans le jeu » quand le
// simulateur applique une règle précise. Les taux et seuils du jeu sont des simplifications pédagogiques.
export const GLOSSARY_CATEGORIES = {
  credit: 'Le crédit',
  achat: 'L\'achat',
  location: 'La location',
  impots: 'Les impôts',
  vente: 'La revente',
  jeu: 'Dans le jeu',
};

export const GLOSSARY = [
  // ── Le crédit
  { id: 'credit', category: 'credit', term: 'Crédit immobilier',
    short: 'Un prêt de la banque pour acheter un bien, remboursé chaque mois pendant des années.',
    long: 'Tu empruntes une somme à la banque et tu la rends par petits morceaux (les mensualités), avec un supplément : les intérêts. Tant que le prêt n\'est pas fini, le bien sert de garantie à la banque.',
    inGame: 'Durée de 10 à 30 ans. La banque accepte ou refuse ton dossier et t\'explique pourquoi.' },
  { id: 'mensualite', category: 'credit', term: 'Mensualité',
    short: 'La somme que tu paies à la banque chaque mois.',
    long: 'Elle reste la même pendant tout le prêt. Elle contient trois choses : du capital remboursé, des intérêts et l\'assurance emprunteur.' },
  { id: 'capital-rembourse', category: 'credit', term: 'Capital remboursé',
    short: 'La part de ta mensualité qui diminue vraiment ta dette. Cet argent n\'est pas perdu : il t\'enrichit.',
    long: 'Chaque mois, une partie de la mensualité rembourse la somme empruntée. Ta dette baisse, donc la part du bien qui t\'appartient réellement augmente. Au début du prêt cette part est petite, elle grossit avec le temps.',
    inGame: 'Affiché séparément de l\'effort d\'épargne, car ce n\'est pas une dépense : c\'est de la richesse qui se construit.' },
  { id: 'interets', category: 'credit', term: 'Intérêts',
    short: 'Le prix que tu paies à la banque pour lui avoir emprunté de l\'argent.',
    long: 'Ils sont calculés sur ce qu\'il te reste à rembourser. Ils sont donc plus élevés au début du prêt. C\'est une vraie dépense, mais elle est déductible de tes revenus de loyers pour le calcul de l\'impôt.' },
  { id: 'taux', category: 'credit', term: 'Taux d\'intérêt',
    short: 'Le pourcentage que la banque te fait payer chaque année sur la somme empruntée.',
    long: 'Plus il est bas, moins le crédit coûte cher. Il change selon les années : un même bien peut être facile à financer une année et bien plus cher à financer une autre.',
    inGame: 'Le taux dépend de l\'année de jeu et de la durée choisie.' },
  { id: 'taeg', category: 'credit', term: 'TAEG',
    short: 'Le vrai coût du crédit en pourcentage : intérêts, assurance et frais compris.',
    long: 'Le taux annoncé ne dit pas tout. Le TAEG (taux annuel effectif global) ajoute l\'assurance et les frais de dossier. C\'est le chiffre à comparer entre deux offres.' },
  { id: 'assurance-emprunteur', category: 'credit', term: 'Assurance emprunteur',
    short: 'Une assurance qui rembourse la banque si tu ne peux plus payer (décès, invalidité).',
    long: 'Les banques l\'exigent presque toujours. Elle s\'ajoute à la mensualité.' },
  { id: 'apport', category: 'credit', term: 'Apport',
    short: 'L\'argent que tu mets de ta poche au départ, pour ne pas tout emprunter.',
    long: 'Plus l\'apport est élevé, moins tu empruntes, et plus la mensualité est légère. Les banques demandent en général au moins de quoi couvrir les frais de notaire.',
    inGame: 'Tu le paies en InvestCoins (1 🪙 = 20 € dans l\'Immobilier).' },
  { id: 'endettement', category: 'credit', term: 'Taux d\'endettement',
    short: 'La part de tes revenus qui part en remboursement de crédits.',
    long: 'La banque calcule : mensualités ÷ revenus. Au-delà d\'un certain seuil, elle refuse. Elle ne compte qu\'une partie des loyers que le bien rapportera, par prudence.' },
  { id: 'reste-a-vivre', category: 'credit', term: 'Reste à vivre',
    short: 'Ce qu\'il te reste chaque mois une fois le crédit et tes dépenses courantes payés.',
    long: 'Même si ton taux d\'endettement est correct, la banque vérifie qu\'il te reste assez pour vivre.' },
  { id: 'capital-restant', category: 'credit', term: 'Capital restant dû',
    short: 'Ce que tu dois encore à la banque à un instant donné.',
    long: 'Au début, il baisse lentement ; à la fin, plus vite. Quand tu vends, la banque récupère cette somme sur le prix de vente.' },
  { id: 'levier', category: 'credit', term: 'Effet de levier',
    short: 'Acheter un bien plus cher que ce que tu possèdes grâce au crédit.',
    long: 'Si le bien prend de la valeur, tu gagnes sur toute sa valeur alors que tu n\'as avancé qu\'une partie. Mais s\'il en perd, ou si les loyers ne suffisent pas, tu perds aussi plus : le levier agit dans les deux sens.' },

  // ── L'achat
  { id: 'frais-notaire', category: 'achat', term: 'Frais de notaire',
    short: 'Les frais payés à l\'achat, surtout des taxes reversées à l\'État.',
    long: 'Le notaire authentifie la vente. La plus grande partie de ces frais sont des taxes. Ils sont plus élevés dans l\'ancien que dans le neuf.',
    inGame: 'Environ 7,5 % du prix dans l\'ancien, 2,5 % dans le neuf (simplification).' },
  { id: 'frais-dossier', category: 'achat', term: 'Frais de dossier',
    short: 'Ce que la banque facture pour monter ton prêt.',
    long: 'C\'est une petite somme payée une seule fois, au début.' },
  { id: 'expertise', category: 'achat', term: 'Expertise',
    short: 'Une visite d\'un professionnel qui repère les défauts cachés avant que tu achètes.',
    long: 'Une annonce ne dit pas tout : humidité, toiture, électricité… L\'expertise coûte un peu, mais peut t\'éviter une grosse surprise de travaux.' },
  { id: 'travaux', category: 'achat', term: 'Travaux',
    short: 'Les dépenses pour remettre un bien en état.',
    long: 'Les travaux annoncés sont dans l\'annonce. Ceux qui sont cachés apparaissent après l\'achat. Un bien à rénover est moins cher, mais te coûte du temps et de l\'argent.' },
  { id: 'bonne-affaire', category: 'achat', term: 'Vente pressée',
    short: 'Un vendeur qui doit vendre vite (succession, divorce, mutation) et accepte un prix plus bas.',
    long: 'Ces occasions existent dans la réalité. Un prix plus bas améliore le rendement, mais vérifie toujours l\'état du bien.' },

  // ── La location
  { id: 'cash-flow', category: 'location', term: 'Cash-flow',
    short: 'L\'argent qui entre moins l\'argent qui sort, chaque mois, pour un bien.',
    long: 'Loyers encaissés, moins charges, moins mensualité du crédit, moins impôts. S\'il est négatif, tu dois compléter de ta poche.' },
  { id: 'effort-epargne', category: 'location', term: 'Effort d\'épargne mensuel',
    short: 'Ce que tu dois ajouter chaque mois pour que le bien « tienne » quand les loyers ne suffisent pas.',
    long: 'Avec un crédit long, un cash-flow négatif est normal : la mensualité contient du capital remboursé, qui te constitue un patrimoine. L\'effort d\'épargne est donc une façon d\'épargner, à condition que le bien garde sa valeur et reste loué.',
    inGame: 'Calculé sur un mois normal, sans les événements exceptionnels (dépôt de garantie, travaux imprévus…).' },
  { id: 'loyer', category: 'location', term: 'Loyer',
    short: 'La somme que le locataire te paie chaque mois.',
    long: 'Il dépend de la ville, du quartier, de la taille, de l\'état et de la performance énergétique. Un loyer trop haut allonge le temps sans locataire.' },
  { id: 'rendement-brut', category: 'location', term: 'Rendement brut',
    short: 'Les loyers d\'une année divisés par le prix d\'achat.',
    long: 'C\'est un repère rapide pour comparer deux biens. Il ignore les charges, les impôts et le crédit ; le rendement réel est plus bas.' },
  { id: 'rendement-metropole', category: 'location', term: 'Pourquoi les grandes villes rapportent moins',
    short: 'Les métropoles chères ont des rendements plus faibles : le prix monte plus vite que les loyers.',
    long: 'Dans une grande ville très demandée, les logements sont chers mais les loyers ne le sont pas dans les mêmes proportions : le rendement brut tourne souvent autour de 3 à 5 %. En contrepartie, le logement se loue vite et son prix a tendance à tenir dans la durée. Dans une petite ville, le rendement est plus élevé, mais le risque de mois sans locataire ou de baisse de prix aussi. Quand les taux de crédit sont élevés, les métropoles s\'autofinancent très difficilement : c\'est réaliste, pas une erreur du jeu.',
    inGame: 'Marvelle (métropole) a volontairement un rendement faible ; Ternelle ou Brumevalle rapportent plus, avec plus de risque.' },
  { id: 'vacance', category: 'location', term: 'Vacance locative',
    short: 'Les mois où le logement est vide : pas de loyer, mais les charges continuent.',
    long: 'Elle est plus courte dans une ville où il y a beaucoup de demande (zone tendue) et plus longue dans une ville qui se vide. Baisser le loyer raccourcit la vacance.' },
  { id: 'zone-tendue', category: 'location', term: 'Zone tendue',
    short: 'Une zone où il y a bien plus de demandeurs de logements que de logements.',
    long: 'Les règles y sont différentes : par exemple le préavis du locataire y est d\'un mois au lieu de trois.' },
  { id: 'charges-recuperables', category: 'location', term: 'Charges récupérables',
    short: 'Des frais que tu avances mais que le locataire te rembourse (eau, entretien des parties communes…).',
    long: 'Elles n\'ont pas d\'effet sur ton résultat, sauf quand le logement est vide ou que le locataire ne paie pas.' },
  { id: 'charges-non-recuperables', category: 'location', term: 'Charges non récupérables',
    short: 'Les frais qui restent pour toi : taxe foncière, assurance du propriétaire, entretien, part de copropriété.',
    long: 'Elles pèsent sur ton cash-flow chaque année, que le bien soit loué ou non.' },
  { id: 'taxe-fonciere', category: 'location', term: 'Taxe foncière',
    short: 'Un impôt local que paie chaque année le propriétaire.',
    long: 'Elle dépend de la commune et de la taille du bien. Elle est déductible de tes revenus de loyers.' },
  { id: 'depot-garantie', category: 'location', term: 'Dépôt de garantie',
    short: 'Une somme versée par le locataire, gardée « en dépôt » pour couvrir d\'éventuels dégâts ou impayés.',
    long: 'Ce n\'est pas un revenu : tu dois le rendre en partant, moins les retenues justifiées (dégradations, loyers non payés).',
    inGame: 'Un mois de loyer. Il n\'est jamais compté dans ton cash-flow normal.' },
  { id: 'preavis', category: 'location', term: 'Préavis',
    short: 'Le délai entre l\'annonce du départ du locataire et son départ réel.',
    long: 'Pendant le préavis, le locataire paie son loyer.',
    inGame: 'Un mois en zone tendue ou pour certains motifs, trois mois sinon.' },
  { id: 'impaye', category: 'location', term: 'Loyer impayé',
    short: 'Un loyer que le locataire ne paie pas.',
    long: 'Un simple retard se rattrape souvent le mois suivant. Un impayé qui dure devient une procédure longue : dans le jeu, elle est raccourcie.' },

  // ── Les impôts
  { id: 'revenus-fonciers', category: 'impots', term: 'Revenus fonciers (régime réel)',
    short: 'Les loyers, moins ce que tu peux déduire, forment ce sur quoi tu paies l\'impôt.',
    long: 'On retire des loyers les charges déductibles, la taxe foncière et les intérêts du crédit. Si le résultat est négatif, tu ne paies rien ce mois-là.',
    inGame: 'Calculé par année civile, impôt réglé en décembre. Simplification pédagogique.' },
  { id: 'impot-loyers', category: 'impots', term: 'Impôt sur les loyers',
    short: 'Ton taux d\'impôt sur le revenu (ta « tranche ») plus les prélèvements sociaux, appliqués au résultat foncier.',
    long: 'Plus tes revenus sont élevés, plus cet impôt est élevé.' },
  { id: 'prelevements-sociaux', category: 'impots', term: 'Prélèvements sociaux',
    short: 'Des contributions qui financent la protection sociale, prélevées sur les revenus du patrimoine.',
    long: 'Ils s\'ajoutent à l\'impôt sur le revenu, sur les loyers comme sur les plus-values.',
    inGame: '17,2 % (taux 2026 à reconfirmer).' },
  { id: 'plus-value', category: 'impots', term: 'Plus-value immobilière',
    short: 'Le gain que tu réalises en revendant plus cher que tu n\'as acheté.',
    long: 'On compare le prix de vente avec le prix d\'achat, majoré des frais et travaux. Le gain est ensuite taxé, mais moins quand on garde le bien longtemps.' },
  { id: 'abattement', category: 'impots', term: 'Abattement pour durée de détention',
    short: 'Une remise sur la plus-value taxable, de plus en plus grande selon le nombre d\'années de détention.',
    long: 'Rien avant 5 ans, puis une réduction chaque année. Au bout de 22 ans, plus d\'impôt sur le revenu sur la plus-value ; au bout de 30 ans, plus aucun impôt. Le rythme n\'est pas le même pour l\'impôt sur le revenu et pour les prélèvements sociaux.' },
  { id: 'surtaxe', category: 'impots', term: 'Surtaxe sur les grosses plus-values',
    short: 'Un impôt supplémentaire quand la plus-value imposable dépasse 50 000 €.',
    long: 'Elle augmente par paliers avec le montant.',
    inGame: 'Le lissage entre les paliers est reconstitué et à reconfirmer.' },

  // ── La revente
  { id: 'ira', category: 'vente', term: 'Indemnité de remboursement anticipé',
    short: 'Une pénalité si tu rembourses ta banque avant la fin du prêt, par exemple en vendant.',
    long: 'Elle est plafonnée par la loi : six mois d\'intérêts ou un pourcentage du capital restant, le plus faible des deux.',
    inGame: 'Le plus petit entre 6 mois d\'intérêts et 3 % du capital restant.' },
  { id: 'frais-agence', category: 'vente', term: 'Frais d\'agence',
    short: 'La commission de l\'agent immobilier qui trouve l\'acheteur.',
    long: 'Ils sont libres et varient. Ils sont en général payés par le vendeur.',
    inGame: '5,78 % du prix de vente.' },
  { id: 'dpe', category: 'vente', term: 'DPE (diagnostic de performance énergétique)',
    short: 'Une note de A à G qui dit si le logement consomme peu ou beaucoup d\'énergie.',
    long: 'Les logements les plus mal notés sont progressivement interdits à la location : la note influence donc la valeur du bien et ce que tu peux en faire.',
    inGame: 'Location interdite : classe G depuis 2025, F depuis 2028, E depuis 2034.' },
  { id: 'audit-energetique', category: 'vente', term: 'Audit énergétique',
    short: 'Une étude plus poussée, obligatoire pour vendre certaines maisons mal classées.',
    long: 'Elle concerne les maisons et les immeubles entiers, pas les appartements en copropriété, et s\'est étendue progressivement aux classes F et G, puis E, et bientôt D.',
    inGame: 'Coût de jeu : 800 € (valeur de jeu, non sourcée).' },
  { id: 'decote', category: 'vente', term: 'Décote',
    short: 'Une baisse de prix quand on est obligé de vendre vite.',
    long: 'Un bien vendu en urgence ou aux enchères part souvent sous sa valeur.' },
  { id: 'vente-forcee', category: 'vente', term: 'Vente forcée (saisie)',
    short: 'La vente de ton bien imposée quand tu ne paies plus ton crédit.',
    long: 'Dans la réalité, c\'est une procédure judiciaire bien plus longue que dans le jeu (souvent plus d\'un an) : la banque doit d\'abord te mettre en demeure, puis un tribunal ordonne une vente aux enchères.',
    inGame: 'Alerte après 3 mois d\'impayés, vente à l\'amiable à −12 % proposée d\'abord, puis vente forcée à −25 % après 2 mois de grâce.' },

  // ── Dans le jeu
  { id: 'investcoin', category: 'jeu', term: 'InvestCoin (🪙)',
    short: 'La monnaie du jeu. Dans l\'Immobilier, 1 🪙 vaut 20 €.',
    long: 'Tous les achats, ventes et revenus sont convertis en pièces entières, avec un petit reliquat conservé pour ne rien perdre ni créer.' },
  { id: 'patrimoine-net', category: 'jeu', term: 'Patrimoine net (fonds propres)',
    short: 'La valeur de tes biens moins ce que tu dois à la banque.',
    long: 'C\'est ce qui t\'appartient vraiment. Il augmente quand tu rembourses le capital et quand les prix montent.' },
  { id: 'performance', category: 'jeu', term: 'Performance (classement)',
    short: 'Ton gain rapporté à l\'argent que tu as investi.',
    long: '(Fonds propres + argent encaissé − argent investi) ÷ argent investi. Un gain vendu reste un gain.' },
  { id: 'mode-accelere', category: 'jeu', term: 'Mode accéléré',
    short: 'Le temps passe quand tu le décides : un mois, un an…',
    long: 'Tu peux voir en quelques minutes ce qu\'un investissement donnerait sur de nombreuses années. Les événements aléatoires (départ d\'un locataire, travaux…) sont tirés de façon reproductible.' },
];

export const glossaryById = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));
