// Exemples concrets et « à ne pas confondre avec » : Bourse, crédit, achat, dans le jeu.
// ex : un exemple chiffré simple ; vs : [identifiant du glossaire, différence en une phrase] ou [null, libellé, différence].
// Les chiffres des exemples sont ronds et inventés pour comprendre : ce ne sont pas des taux officiels.
export const FICHES_A = {
  // Bourse
  courtage: { ex: "Tu achètes pour 1 000 € d'actions avec un courtage de 0,5 % : tu paies 5 € à l'achat, puis encore 5 € à la vente.",
    vs: [['taeg', "Le TAEG mesure le coût d'un crédit, pas celui d'un ordre de Bourse."], ['frais-dossier', "Les frais de dossier se paient une fois à l'ouverture d'un crédit."]] },
  pea: { ex: "Tu verses 10 000 € et ils deviennent 13 000 € au bout de 6 ans : en retirant, tu ne paies que les prélèvements sociaux sur les 3 000 € de gain.",
    vs: [['compte-titres', "Le compte-titres n'a ni plafond ni avantage fiscal."], [null, 'Assurance-vie', "Une autre enveloppe, avec ses propres règles : elle n'est pas traitée dans le jeu."]] },
  "compte-titres": { ex: "Tu gagnes 1 000 € en revendant des actions : à 31,4 %, il part 314 € en impôts et prélèvements sociaux.",
    vs: [['pea', "Le PEA est plafonné mais bien moins taxé après 5 ans."], ['flat-tax', "La flat tax est le taux ; le compte-titres est le « tiroir » qui la subit."]] },
  "flat-tax": { ex: "Avec 1 000 € de gain, la part d'impôt sur le revenu est de 128 € (12,8 %) ; les prélèvements sociaux s'y ajoutent.",
    vs: [['prelevements-sociaux', "Les prélèvements sociaux sont une partie de la flat tax, pas un impôt à part."], ['impot-loyers', "Les loyers suivent ton barème, pas la flat tax."]] },
  "impot-crypto": { ex: "Tu échanges du bitcoin contre de l'ethereum : rien à payer. Tu revends l'ethereum contre des euros : c'est là que l'impôt peut s'appliquer.",
    vs: [['echange-crypto', "Un échange crypto contre crypto n'est pas imposé."], ['flat-tax', "La flat tax est le taux appliqué au gain, pas la règle de déclenchement."]] },
  action: { ex: "Une entreprise est découpée en 1 000 actions. En en détenant 10, tu possèdes 1 % de l'entreprise.",
    vs: [['etf', "Un ETF contient de nombreuses actions d'un coup."], ['obligation', "Une obligation est une dette prêtée à l'entreprise, pas une part."]] },
  etf: { ex: "Un ETF qui copie un indice de 500 entreprises : avec 100 €, tu en détiens un tout petit morceau, au lieu de choisir toi-même.",
    vs: [['action', "Une action = une seule entreprise."], ['diversification', "L'ETF est un moyen de se diversifier, pas la diversification elle-même."]] },
  obligation: { ex: "Tu prêtes 1 000 € à une entreprise qui te promet 3 % par an pendant 5 ans, puis te rend ton capital.",
    vs: [['action', "L'action donne une part de propriété, l'obligation une créance."], ['credit', "Dans un crédit, c'est toi qui empruntes."]] },
  crypto: { ex: "Un bitcoin s'achète et se vend 24 h sur 24 : son prix peut bouger de 10 % en une journée.",
    vs: [['stablecoin', "Un stablecoin cherche à rester stable, contrairement à la plupart des cryptos."], ['investcoin', "Les InvestCoins ne sont pas une crypto : c'est la monnaie du jeu."]] },
  volatilite: { ex: "Une action qui varie de ±1 % par jour est peu volatile ; une crypto qui varie de ±8 % l'est beaucoup.",
    vs: [['drawdown', "Le drawdown mesure une chute depuis un sommet ; la volatilité mesure l'agitation du prix."], [null, 'Perte', "Un prix très volatil n'est pas forcément perdant : il est seulement moins prévisible."]] },
  diversification: { ex: "Au lieu de mettre 1 000 € sur une seule action, tu en mets 250 € sur quatre : si l'une chute, les autres amortissent.",
    vs: [['correlation', "Diversifier avec des actifs très corrélés protège mal."], ['etf', "L'ETF est un outil de diversification."]] },
  "cours-cloture": { ex: "Une action cote 98 € le matin du 31 décembre et 100 € à la clôture : son cours de clôture est de 100 €.",
    vs: [['bougie', "Une bougie résume l'ouverture, le plus haut, le plus bas et la clôture."], ['annee-simulee', "L'année simulée est la date de jeu, pas un cours."]] },
  "annee-simulee": { ex: "Tu es en « 2008 » dans le jeu : tu ne vois aucun prix postérieur à 2008, comme un investisseur de l'époque.",
    vs: [['mode-accelere', "Le mode accéléré fait passer le temps plus vite ; l'année simulée est la date en cours."]] },
  "valeur-positions": { ex: "Tu as 10 actions à 50 € et 2 à 100 € : la valeur de tes positions est de 700 €.",
    vs: [['patrimoine-net', "Le patrimoine net ajoute les liquidités et retire les dettes."]] },
  "performance-portefeuille": { ex: "Ton portefeuille passe de 1 000 € à 1 100 € : la performance est de +10 %.",
    vs: [['performance', "La performance du classement a sa propre formule, plus complète."], ['valeur-positions', "La valeur est un montant ; la performance est un pourcentage."]] },

  // Crédit
  credit: { ex: "Tu empruntes 200 000 € sur 25 ans : tu rembourses chaque mois une somme fixe, et la banque se rémunère avec des intérêts.",
    vs: [['pret-personnel', "Le prêt personnel finance une dépense libre, avec une durée courte."], ['credit-fleche', "Le crédit fléché est réservé à un domaine précis du jeu."]] },
  mensualite: { ex: "Pour 200 000 € à 3 % sur 20 ans, la mensualité est d'environ 1 109 €, hors assurance.",
    vs: [['capital-rembourse', "Une partie seulement de la mensualité rembourse le capital."], ['loyer', "Le loyer est ce que tu perçois ; la mensualité est ce que tu paies."]] },
  "capital-rembourse": { ex: "Sur une mensualité de 1 109 €, 609 € peuvent être du capital et 500 € des intérêts en début de crédit.",
    vs: [['interets', "Les intérêts sont le prix du prêt, perdu pour toi."], ['capital-restant', "Le capital restant est ce qu'il te reste à rembourser."]] },
  interets: { ex: "À 3 % par an sur 100 000 € restants, tu paies environ 3 000 € d'intérêts sur la première année.",
    vs: [['taux', "Le taux est le pourcentage ; les intérêts sont le montant en euros."], ['taeg', "Le TAEG ajoute les frais aux intérêts."]] },
  taux: { ex: "Un taux de 3 % sur 100 000 € coûte 3 000 € la première année ; à 4 %, 4 000 €.",
    vs: [['taeg', "Le taux ne compte que les intérêts ; le TAEG inclut les frais."], ['taux-base', "Le taux de base est une référence du jeu, pas ton taux final."]] },
  taeg: { ex: "Deux banques proposent 3 %. L'une a des frais de dossier et une assurance plus chères : son TAEG est plus haut, donc elle coûte plus.",
    vs: [['taux', "Le taux seul cache les frais."], ['assurance-emprunteur', "L'assurance est un des éléments qui font monter le TAEG."]] },
  "assurance-emprunteur": { ex: "Tu paies 30 € par mois en plus de ta mensualité : en cas de coup dur, l'assurance prend le relais auprès de la banque.",
    vs: [['gli', "La GLI protège le propriétaire des loyers impayés ; l'assurance emprunteur protège de l'incapacité à rembourser."]] },
  apport: { ex: "Pour un bien à 200 000 €, tu apportes 30 000 € : tu empruntes 170 000 € (plus les frais de notaire à payer aussi).",
    vs: [['frais-notaire', "L'apport sert souvent à payer ces frais, que la banque ne finance pas toujours."], ['patrimoine-net', "L'apport est une somme donnée ; le patrimoine net est ce qui te reste après dettes."]] },
  endettement: { ex: "Avec 3 000 € de revenus et 900 € de mensualités, ton taux d'endettement est de 30 %.",
    vs: [['reste-a-vivre', "Le reste à vivre est un montant, l'endettement un pourcentage."], ['levier', "Le levier est l'effet du crédit sur ta performance, pas ta capacité à emprunter."]] },
  "reste-a-vivre": { ex: "Avec 2 500 € de revenus, 800 € de crédit et 900 € de dépenses, il te reste 800 € par mois.",
    vs: [['endettement', "Deux ménages peuvent avoir le même endettement et des restes à vivre très différents."], ['cash-flow', "Le cash-flow concerne un investissement, pas tout ton budget."]] },
  "epargne-restante": { ex: "Avec une mensualité de 700 InvestCoins et 1 400 pièces à toi après l'achat, il te reste 2 mensualités : le jeu t'avertit, mais tu peux acheter.",
    vs: [['reste-a-vivre', "Le reste à vivre est un montant par mois ; l'épargne restante est un stock de pièces mis en regard des mensualités."], ['pret-personnel', "Un prêt personnel non remboursé ne compte pas comme de l'épargne : il se rembourse."]] },
  "capital-restant": { ex: "Après 5 ans sur un prêt de 200 000 €, il peut rester environ 170 000 € à rembourser.",
    vs: [['capital-rembourse', "Le capital remboursé est la partie déjà payée."], ['patrimoine-net', "Le net retire cette dette de la valeur du bien."]] },
  levier: { ex: "Tu mets 20 000 € et tu empruntes 80 000 € pour un bien à 100 000 € : s'il gagne 10 %, ton gain est de 50 % de ta mise. Mais une perte est aussi multipliée.",
    vs: [['endettement', "Le levier amplifie les gains comme les pertes ; l'endettement mesure ta charge."], ['appel-de-marge', "L'appel de marge est la conséquence du levier quand ça tourne mal."]] },
  "pret-personnel": { ex: "Tu empruntes 5 000 € sur 3 ans pour une dépense libre : la mensualité est plus lourde que celle d'un crédit immobilier.",
    vs: [['credit', "Le crédit immobilier finance un bien et dure bien plus longtemps."], ['credit-fleche', "Le crédit fléché ne se dépense que dans un domaine."]] },
  "credit-fleche": { ex: "Tu empruntes pour de l'immobilier : tu ne peux pas dépenser ces pièces en crypto tant qu'elles sont réservées.",
    vs: [['pret-personnel', "Le prêt personnel peut être dépensé dans n'importe quel domaine."]] },
  "taux-base": { ex: "Un taux de base de 3 % peut devenir 4,5 % pour un profil plus risqué : le taux de base est le point de départ.",
    vs: [['taux', "Ton taux est celui que tu paies vraiment ; le taux de base est une référence."]] },
  retablissement: { ex: "Après un défaut sur tous tes prêts, la procédure efface la dette contre la perte de tes biens, et tu repars de zéro.",
    vs: [['defaut-paiement', "Le défaut est la cause, le rétablissement est un remède extrême."]] },
  "pret-portefeuille": { ex: "Ton portefeuille de 10 000 € sert de garantie pour emprunter 4 000 € sans rien vendre.",
    vs: [['pret-personnel', "Le prêt personnel n'a pas de garantie financière."], ['appel-de-marge', "Si le portefeuille chute, la banque peut te demander des garanties."]] },
  "appel-de-marge": { ex: "Ton portefeuille perd 30 % : la banque te demande de rembourser une partie ou d'ajouter des garanties, sinon elle vend pour toi.",
    vs: [['liquidation', "L'appel de marge est l'avertissement ; la liquidation est la vente forcée."], ['defaut-paiement', "Le défaut est un retard de paiement ; l'appel de marge, une baisse de garantie."]] },
  "defaut-paiement": { ex: "Tu rates plusieurs mensualités de suite : la banque prévient, puis peut exiger de vendre ce que tu as financé.",
    vs: [['impaye', "L'impayé de loyer concerne le locataire, le défaut concerne ton crédit."], ['retablissement', "Le rétablissement est ce qui vient après un défaut grave."]] },
  "remboursement-anticipe": { ex: "Tu as hérité de 20 000 € et tu les rends à ta banque : tu paies moins d'intérêts par la suite, parfois avec une indemnité.",
    vs: [['ira', "L'IRA est la pénalité possible quand on rembourse avant la fin."], ['capital-rembourse', "Le capital remboursé est le suivi normal, mensualité après mensualité."]] },

  // Achat
  "frais-notaire": { ex: "Pour un logement ancien à 200 000 €, compte environ 15 000 € de frais de notaire en plus (surtout des taxes).",
    vs: [['frais-agence', "L'agence est rémunérée pour la vente, le notaire pour l'acte."], ['frais-dossier', "Les frais de dossier sont facturés par la banque."]] },
  "frais-dossier": { ex: "La banque facture 1 000 € pour monter ton dossier de crédit, payables une seule fois.",
    vs: [['frais-notaire', "Les frais de notaire servent l'acte de vente."], ['taeg', "Le TAEG intègre ces frais."]] },
  expertise: { ex: "Un expert estime un bien à 190 000 € alors que le vendeur en demande 200 000 € : tu as un argument pour négocier.",
    vs: [['dpe', "Le DPE évalue l'énergie ; l'expertise évalue la valeur."]] },
  "valeur-verte": { ex: "Deux appartements identiques : celui classé B se vend plus cher que celui classé F, car les travaux à venir sont moindres.",
    vs: [['dpe', "Le DPE est la note ; la valeur verte est son effet sur le prix."]] },
  travaux: { ex: "Un bien à 150 000 € nécessitant 20 000 € de travaux revient à 170 000 € : compare-le au prix d'un bien déjà rénové.",
    vs: [['audit-energetique', "L'audit chiffre une partie des travaux d'énergie."]] },
  "bonne-affaire": { ex: "Un vendeur pressé accepte 10 % de moins : l'avantage est réel, mais le bien peut cacher un défaut.",
    vs: [['vente-forcee', "Une vente forcée est imposée par un créancier, pas choisie."], ['decote', "La décote est le rabais lui-même."]] },

  // Dans le jeu
  investcoin: { ex: "Tu commences avec 10 000 InvestCoins : tu peux les investir dans le jeu, mais jamais les retirer en euros.",
    vs: [['crypto', "Une crypto s'échange sur des marchés réels ; l'InvestCoin n'existe que dans le jeu."]] },
  "patrimoine-net": { ex: "Un bien à 200 000 € avec 150 000 € de prêt restant, plus 5 000 € en liquidités : patrimoine net = 55 000 €.",
    vs: [['valeur-positions', "La valeur des positions oublie les dettes et les liquidités."], ['performance', "La performance est un pourcentage."]] },
  performance: { ex: "Tu as investi 10 000 InvestCoins et ton résultat est de 11 500 : ta performance est de +15 %.",
    vs: [['performance-portefeuille', "Le portefeuille Bourse a sa propre mesure."], ['patrimoine-net', "Le patrimoine net est un montant."]] },
  "mode-accelere": { ex: "Au lieu d'attendre, tu fais avancer le temps de jeu d'un an pour voir l'effet d'un choix.",
    vs: [['annee-simulee', "L'année simulée est la date courante, pas la vitesse."]] },
};
