// Spécification OpenAPI 3.0 de l'API (générée depuis un tableau de routes).
// Le test tests/openapi.test.ts vérifie que ce tableau couvre TOUTES les
// routes réellement montées dans l'application : ajouter une route sans la
// décrire ici fait échouer les tests.

type Row = [method: 'get' | 'post' | 'put' | 'patch' | 'delete', path: string, tag: string, summary: string, access?: 'public' | 'admin'];

export const ROUTES: Row[] = [
  ['get', '/auth/signup-config', 'Compte', 'Configuration de l\'inscription (invitation ou non)', 'public'],
  ['post', '/auth/register', 'Compte', 'Créer un compte', 'public'],
  ['post', '/auth/login', 'Compte', 'Se connecter (renvoie un jeton, ou demande le code 2FA)', 'public'],
  ['post', '/auth/verify-email', 'Compte', 'Valider l\'e-mail avec le code à 6 chiffres (ouvre la session)', 'public'],
  ['post', '/auth/resend-code', 'Compte', 'Renvoyer le code de vérification', 'public'],
  ['post', '/auth/save-preferences', 'Compte', 'Enregistrer le pseudo et les préférences (session requise, ouverte par verify-email)'],
  ['get', '/realestate/favorites', 'Immobilier', 'Mes annonces favorites (année de jeu en cours)'],
  ['put', '/realestate/favorites/{id}', 'Immobilier', 'Ajouter une annonce aux favoris'],
  ['delete', '/realestate/favorites/{id}', 'Immobilier', 'Retirer une annonce des favoris'],
  ['get', '/realestate/saved-searches', 'Immobilier', 'Mes recherches enregistrées (avec le nombre de nouvelles annonces)'],
  ['post', '/realestate/saved-searches', 'Immobilier', 'Enregistrer une recherche'],
  ['post', '/realestate/saved-searches/{id}/seen', 'Immobilier', 'Marquer les annonces d\'une recherche comme vues'],
  ['delete', '/realestate/saved-searches/{id}', 'Immobilier', 'Supprimer une recherche enregistrée'],
  ['post', '/auth/forgot-password', 'Compte', 'Demander une réinitialisation du mot de passe', 'public'],
  ['post', '/auth/reset-password', 'Compte', 'Réinitialiser le mot de passe', 'public'],
  ['post', '/auth/validate-invite', 'Compte', 'Vérifier (sans le consommer) un code d\'invitation : répond seulement valide ou non', 'public'],
  ['post', '/auth/2fa/login-verify', 'Compte', 'Terminer la connexion avec le code 2FA', 'public'],
  ['post', '/auth/logout', 'Compte', 'Se déconnecter (efface les cookies de session)', 'public'],
  ['post', '/auth/impersonation/stop', 'Compte', 'Quitter une impersonation et retrouver sa session administrateur'],
  ['post', '/auth/session/upgrade', 'Compte', 'Échanger un ancien jeton (Bearer) contre un cookie de session httpOnly'],
  ['get', '/auth/me', 'Compte', 'Profil de l\'utilisateur connecté'],
  ['post', '/auth/set-free-domain', 'Compte', 'Choisir le domaine gratuit'],
  ['post', '/auth/2fa/setup', 'Compte', 'Démarrer l\'activation de la 2FA'],
  ['post', '/auth/2fa/verify-setup', 'Compte', 'Confirmer l\'activation de la 2FA'],
  ['post', '/auth/2fa/disable', 'Compte', 'Désactiver la 2FA'],
  ['get', '/auth/me/export', 'RGPD', 'Télécharger toutes ses données (JSON)'],
  ['post', '/auth/me/delete', 'RGPD', 'Supprimer son compte (mot de passe + phrase SUPPRIMER)'],
  ['post', '/billing/create-checkout-session', 'Abonnement', 'Ouvrir le paiement Stripe'],
  ['post', '/billing/create-portal-session', 'Abonnement', 'Ouvrir le portail client Stripe'],
  ['post', '/billing/webhook', 'Abonnement', 'Webhook Stripe (signature vérifiée)', 'public'],
  ['get', '/economy/balance', 'InvestCoins', 'Solde de pièces'],
  ['get', '/economy/history', 'InvestCoins', 'Historique des transactions'],
  ['post', '/economy/daily-reward', 'InvestCoins', 'Récompense quotidienne'],
  ['get', '/economy/first-steps', 'InvestCoins', 'Bonus « premiers pas » : état et montants'],
  ['get', '/economy/admin/coins-by-domain', 'InvestCoins', 'Statistiques admin des pièces par domaine', 'admin'],
  ['post', '/education/submit-quiz', 'Éducation', 'Soumettre un quiz (corrigé par le serveur, récompense unique)'],
  ['post', '/education/complete-chapter', 'Éducation', 'Ancienne route (410, ne récompense plus)'],
  ['post', '/education/complete-domain', 'Éducation', 'Ancienne route (410, ne récompense plus)'],
  ['get', '/social/me', 'Social', 'Mon code ami et mes compteurs'],
  ['get', '/social/tag', 'Social', 'Mon identifiant Pseudo#tag (et mes droits de changement)'],
  ['post', '/social/tag', 'Social', 'Choisir mon # (membres Pro : 1 changement par mois, règles vérifiées par le serveur)'],
  ['get', '/social/tag/history', 'Social', 'Historique de mes #'],
  ['get', '/profile', 'Profil', 'Mon profil : nom, bio, e-mail, pseudo, photo'],
  ['patch', '/profile', 'Profil', 'Modifier mon nom et ma bio (un champ absent n\'est pas touché ; l\'e-mail ne se change pas ici)'],
  ['post', '/profile/avatar', 'Profil', 'Envoyer ma photo (corps brut JPG/PNG/WebP, 3 Mo max ; ré-encodée et nettoyée côté serveur)'],
  ['delete', '/profile/avatar', 'Profil', 'Supprimer ma photo'],
  ['get', '/profile/avatar/{avatarId}', 'Profil', 'Image d\'une photo (identifiant secret)', 'public'],
  ['post', '/profile/email/request', 'Profil', 'Demander un changement d\'e-mail (mot de passe ; code envoyé à la nouvelle adresse)'],
  ['post', '/profile/email/confirm', 'Profil', 'Confirmer le changement d\'e-mail avec le code reçu'],
  ['post', '/social/privacy', 'Social', 'Montrer ou masquer ma couronne Pro aux autres joueurs'],
  ['get', '/social/friends', 'Social', 'Mes amis (nom, niveau, XP)'],
  ['get', '/social/friends/ranking', 'Social', 'Classement entre amis (moi + amis, par XP d\'éducation)'],
  ['get', '/social/requests', 'Social', 'Demandes d\'amis reçues et envoyées'],
  ['post', '/social/requests', 'Social', 'Envoyer une demande avec un identifiant Pseudo#tag ou un code ami exact'],
  ['post', '/social/requests/{id}/accept', 'Social', 'Accepter une demande'],
  ['post', '/social/requests/{id}/decline', 'Social', 'Refuser une demande'],
  ['delete', '/social/requests/{id}', 'Social', 'Annuler une demande envoyée'],
  ['delete', '/social/friends/{userId}', 'Social', 'Retirer un ami'],
  ['get', '/social/blocks', 'Social', 'Joueurs bloqués'],
  ['post', '/social/blocks', 'Social', 'Bloquer un joueur'],
  ['delete', '/social/blocks/{userId}', 'Social', 'Débloquer un joueur'],
  ['get', '/social/guild', 'Social', 'Ma guilde et son classement interne'],
  ['post', '/social/guilds', 'Social', 'Créer une guilde'],
  ['post', '/social/guilds/join', 'Social', 'Rejoindre une guilde avec un code d\'invitation'],
  ['post', '/social/guilds/leave', 'Social', 'Quitter ma guilde'],
  ['post', '/social/guilds/kick', 'Social', 'Retirer un membre (propriétaire)'],
  ['post', '/social/guilds/transfer', 'Social', 'Passer la guilde à un membre (propriétaire)'],
  ['post', '/social/guilds/invite/regenerate', 'Social', 'Changer le code d\'invitation (propriétaire)'],
  ['delete', '/social/guilds', 'Social', 'Dissoudre la guilde (propriétaire)'],
  ['get', '/trading/domains', 'Bourse / Crypto', 'Domaines de trading'],
  ['get', '/trading/assets', 'Bourse / Crypto', 'Actifs disponibles'],
  ['get', '/trading/portfolio', 'Bourse / Crypto', 'Portefeuille virtuel'],
  ['get', '/trading/history', 'Bourse / Crypto', 'Historique d\'un titre (borné à l\'année simulée)'],
  ['post', '/trading/buy', 'Bourse / Crypto', 'Acheter'],
  ['post', '/trading/sell', 'Bourse / Crypto', 'Vendre'],
  ['post', '/trading/quote', 'Bourse / Crypto', 'Aperçu d\'un ordre : frais, impôt sur la plus-value, explication'],
  ['post', '/trading/advance-year', 'Bourse / Crypto', 'Avancer d\'un an'],
  ['get', '/trading/leaderboard', 'Bourse / Crypto', 'Classement'],
  ['get', '/realestate/state', 'Immobilier', 'État de la partie'],
  ['post', '/realestate/start', 'Immobilier', 'Démarrer une partie'],
  ['get', '/realestate/listings', 'Immobilier', 'Annonces'],
  ['get', '/realestate/listings/{id}', 'Immobilier', 'Détail d\'une annonce'],
  ['post', '/realestate/listings/{id}/expertise', 'Immobilier', 'Commander une expertise'],
  ['post', '/realestate/purchase/preview', 'Immobilier', 'Simuler un achat'],
  ['post', '/realestate/purchase', 'Immobilier', 'Acheter un bien'],
  ['get', '/realestate/properties', 'Immobilier', 'Mes biens'],
  ['post', '/realestate/properties/{id}/pay-works', 'Immobilier', 'Payer des travaux'],
  ['post', '/realestate/properties/{id}/list', 'Immobilier', 'Mettre en location'],
  ['post', '/realestate/properties/{id}/reprice', 'Immobilier', 'Modifier le loyer'],
  ['get', '/realestate/properties/{id}/statements', 'Immobilier', 'Relevés du bien'],
  ['post', '/realestate/time/advance', 'Immobilier', 'Avancer d\'un mois'],
  ['get', '/realestate/summary', 'Immobilier', 'Bilan du mois'],
  ['post', '/realestate/properties/{id}/gli', 'Immobilier', 'Activer/désactiver l\'assurance loyers impayés'],
  ['post', '/realestate/properties/{id}/landlord-notice', 'Immobilier', 'Donner congé au locataire'],
  ['get', '/realestate/events', 'Immobilier', 'Événements'],
  ['post', '/realestate/properties/{id}/sell', 'Immobilier', 'Mettre un bien en vente'],
  ['get', '/realestate/properties/{id}/sell/options', 'Immobilier', 'Options de prix de vente'],
  ['post', '/realestate/properties/{id}/sell/reprice', 'Immobilier', 'Modifier le prix de vente'],
  ['get', '/realestate/properties/{id}/renovate/preview', 'Immobilier', 'Devis de rénovation énergétique'],
  ['post', '/realestate/properties/{id}/renovate', 'Immobilier', 'Lancer la rénovation'],
  ['post', '/realestate/distress/sell', 'Immobilier', 'Vente en difficulté'],
  ['get', '/realestate/sales', 'Immobilier', 'Historique des ventes'],
  ['get', '/realestate/leaderboard', 'Immobilier', 'Classement'],
  ['get', '/bank/overview', 'Banque', 'Vue d\'ensemble (prêts, plafonds, blocage)'],
  ['get', '/bank/events', 'Banque', 'Événements bancaires récents'],
  ['post', '/bank/personal/quote', 'Banque', 'Devis de prêt personnel'],
  ['post', '/bank/personal/borrow', 'Banque', 'Emprunter (prêt personnel)'],
  ['post', '/bank/portfolio/quote', 'Banque', 'Devis de prêt sur portefeuille'],
  ['post', '/bank/portfolio/borrow', 'Banque', 'Emprunter sur portefeuille'],
  ['post', '/bank/portfolio/loans/{id}/repay', 'Banque', 'Rembourser un prêt sur portefeuille'],
  ['post', '/bank/recovery/preview', 'Banque', 'Aperçu de la procédure de rétablissement'],
  ['post', '/bank/recovery/start', 'Banque', 'Lancer la procédure de rétablissement (RETABLISSEMENT)'],
  ['post', '/bank/loans/{id}/repay', 'Banque', 'Rembourser un prêt'],
  ['get', '/flags', 'Drapeaux', 'Drapeaux de fonctionnalité évalués pour moi'],
  ['post', '/feedback', 'Retours', 'Envoyer un retour (bug, idée, 👍/👎)'],
  ['get', '/announcements', 'Retours', 'Annonces et nouveautés publiées', 'public'],
  ['get', '/admin/feedback', 'Administration', 'Retours des utilisateurs (filtres, pagination)', 'admin'],
  ['post', '/admin/feedback/{id}', 'Administration', 'Changer le statut d\'un retour (nouveau, vu, traité, refusé)', 'admin'],
  ['get', '/admin/announcements', 'Administration', 'Liste des annonces (publiées ou non)', 'admin'],
  ['post', '/admin/announcements', 'Administration', 'Créer une annonce', 'admin'],
  ['put', '/admin/announcements/{id}', 'Administration', 'Modifier / publier / dépublier une annonce', 'admin'],
  ['delete', '/admin/announcements/{id}', 'Administration', 'Supprimer une annonce', 'admin'],
  ['post', '/tools/monte-carlo', 'Outils de risque', 'Simulation Monte Carlo (P10 / médiane / P90), sans compte', 'public'],
  ['post', '/tools/stress-test', 'Outils de risque', 'Test de résistance sur les crises historiques, sans compte', 'public'],
  ['post', '/tools/risk-score', 'Outils de risque', 'Score de risque décomposé par facteur, sans compte', 'public'],
  ['get', '/tools/correlation', 'Outils de risque', 'Corrélations entre les actifs du jeu, sans compte', 'public'],
  ['get', '/risk/portfolio', 'Outils de risque', 'Risque de mon portefeuille simulé (score, répartition, crises)'],
  ['get', '/notifications', 'Notifications', 'Mes notifications (événements du jeu et de la sécurité)'],
  ['post', '/notifications/read', 'Notifications', 'Marquer des notifications comme lues (ids ou all)'],
  ['get', '/onboarding', 'Accueil', 'Checklist d\'accueil (étapes réelles, récompenses, profil)'],
  ['post', '/onboarding/claim', 'Accueil', 'Récupérer les récompenses des étapes terminées'],
  ['post', '/onboarding/profile', 'Accueil', 'Enregistrer le profil d\'investisseur (et obtenir un conseil de départ)'],
  ['get', '/overview', 'Accueil', 'Vue d\'ensemble réelle : pièces, Bourse, Crypto, Immobilier, dette, risque'],
  ['get', '/crypto/state', 'Crypto', 'État du domaine Crypto (compte, date simulée, dates de départ, unités de temps)'],
  ['post', '/crypto/account', 'Crypto', 'Créer mon compte Crypto en choisissant une date de départ'],
  ['get', '/crypto/assets', 'Crypto', 'Actifs cotés à ma date simulée (recherche, catégorie, tri)'],
  ['get', '/crypto/assets/{symbol}', 'Crypto', 'Fiche d\'un actif (jamais d\'information postérieure à ma date simulée)'],
  ['get', '/crypto/candles', 'Crypto', 'Bougies par lots (symbol, tf, before, limit), bornées à ma date simulée'],
  ['get', '/crypto/compare', 'Crypto', 'Comparaison de 2 à 4 actifs rebasés à 100'],
  ['get', '/crypto/quote', 'Crypto', 'Chiffrer un ordre au marché (prix effectif, écart, glissement, frais)'],
  ['get', '/crypto/portfolio', 'Crypto', 'Mon portefeuille Crypto (positions, prix de revient, plus-values, répartition, ordres en attente)'],
  ['get', '/crypto/orders', 'Crypto', 'Mes ordres (statut optionnel)'],
  ['post', '/crypto/orders', 'Crypto', 'Passer un ordre (market, limit, stop_loss, take_profit) ; idempotent via clientOrderId'],
  ['delete', '/crypto/orders/{id}', 'Crypto', 'Annuler un de mes ordres en attente'],
  ['post', '/crypto/swap', 'Crypto', 'Échanger une crypto contre une autre (sans impôt, frais seulement)'],
  ['get', '/crypto/events', 'Crypto', 'Journal du marché : événements franchis par ma date simulée, avec leçon'],
  ['get', '/crypto/loan', 'Crypto', 'Mon prêt sur portefeuille Crypto (garantie, LTV, appel de marge)'],
  ['post', '/crypto/loan/quote', 'Crypto', 'Simuler un prêt sur mon portefeuille Crypto (30 % de la valeur)'],
  ['post', '/crypto/loan/borrow', 'Crypto', 'Emprunter sur mon portefeuille Crypto'],
  ['post', '/crypto/loan/repay', 'Crypto', 'Rembourser mon prêt Crypto'],
  ['get', '/crypto/leaderboard', 'Crypto', 'Classement Crypto en %, par période simulée, net de dettes, levier affiché'],
  ['post', '/crypto/time/advance', 'Crypto', 'Avancer ma date simulée d\'un jour, d\'une semaine ou d\'un mois (le serveur décide, jamais en arrière)'],
  ['get', '/admin/users', 'Administration', 'Liste des utilisateurs (recherche, filtres, pagination)', 'admin'],
  ['get', '/admin/users/{id}', 'Administration', 'Fiche d\'un utilisateur (consultation tracée)', 'admin'],
  ['post', '/admin/users/{id}/pro', 'Administration', 'Activer/retirer le statut Pro manuel', 'admin'],
  ['post', '/admin/users/{id}/disable', 'Administration', 'Suspendre un compte (motif obligatoire)', 'admin'],
  ['post', '/admin/users/{id}/enable', 'Administration', 'Réactiver un compte', 'admin'],
  ['post', '/admin/users/{id}/coins', 'Administration', 'Ajuster les pièces (motif obligatoire, plafonné)', 'admin'],
  ['post', '/admin/users/{id}/impersonate', 'Administration', 'Voir le site comme cet utilisateur (lecture seule, 15 min, tracé)', 'admin'],
  ['get', '/admin/audit', 'Administration', 'Journal d\'audit (filtres, pagination)', 'admin'],
  ['get', '/admin/stats', 'Administration', 'Statistiques globales', 'admin'],
  ['get', '/admin/billing', 'Administration', 'Abonnements et paiements', 'admin'],
  ['get', '/admin/alerts', 'Administration', 'Alertes proactives', 'admin'],
  ['get', '/admin/system', 'Administration', 'Santé du serveur et contrôles de configuration', 'admin'],
  ['get', '/admin/flags', 'Administration', 'Liste des drapeaux de fonctionnalité', 'admin'],
  ['put', '/admin/flags/{key}', 'Administration', 'Créer ou modifier un drapeau', 'admin'],
  ['delete', '/admin/flags/{key}', 'Administration', 'Supprimer un drapeau', 'admin'],
  ['get', '/bank/admin/stats', 'Banque', 'Statistiques admin de la banque', 'admin'],
];

export const buildOpenApiSpec = () => {
  const paths: Record<string, any> = {};
  for (const [method, path, tag, summary, access] of ROUTES) {
    const params = [...path.matchAll(/\{(\w+)\}/g)].map((m) => ({
      name: m[1], in: 'path', required: true, schema: { type: 'string' },
    }));
    const responses: Record<string, any> = { '200': { description: 'Succès' } };
    if (access !== 'public') responses['401'] = { description: 'Jeton absent ou invalide' };
    if (access === 'admin') responses['403'] = { description: 'Réservé aux administrateurs avec 2FA' };
    paths[`/api/v1${path}`] = {
      ...paths[`/api/v1${path}`],
      [method]: {
        tags: [tag],
        summary,
        ...(params.length ? { parameters: params } : {}),
        ...(access === 'public' ? { security: [] } : {}),
        responses,
      },
    };
  }
  return {
    openapi: '3.0.3',
    info: {
      title: 'InvestKit API',
      version: '1.0.0',
      description: 'API de la plateforme InvestKit. Les pièces (InvestCoins) sont une monnaie de jeu : ni boutique, ni retrait, ni achat en argent réel.',
    },
    servers: [{ url: '/' }],
    security: [{ bearerAuth: [] }],
    components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } },
    paths,
  };
};
